CREATE TABLE IF NOT EXISTS `CAMFIC` (
  `CAMFICCOD` mediumint(9) NOT NULL COMMENT 'CÓDIGO',
  `CAMFICEST` mediumint(9) NOT NULL COMMENT 'ESTADO',
  `CAMFICNOM` varchar(100) COLLATE utf8_spanish_ci NOT NULL COMMENT 'CAMPAÑA',
  `CAMFICFDE` date NOT NULL COMMENT 'FECHA INICIO',
  `CAMFICFHA` date NOT NULL COMMENT 'FECHA FINAL',
  `CAMFICCOL` char(10) COLLATE utf8_spanish_ci NOT NULL COMMENT 'FORMULARIO COLOR',
  `CAMFICFO1` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'FORMULARIO 1',
  `CAMFICFO2` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'FORMULARIO 2',
  `CAMFICFO3` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'FORMULARIO 3',
  `CAMFICFO4` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'FORMULARIO 4',
  `CAMFICFO5` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'FORMULARIO 5',
  `CAMFICFO6` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'FORMULARIO 6',
  `CAMFICFO7` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'FORMULARIO 7',
  `CAMFICFO8` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'FORMULARIO 8',
  `CAMFICOBS` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN',
  `CAMFICAUS` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
  `CAMFICAFH` datetime NOT NULL COMMENT 'FECHA HORA',
  `CAMFICAIP` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='CAMPAÑA';

CREATE TABLE IF NOT EXISTS `CAMFICA` (
  `CAMFICACOD` int(11) NOT NULL COMMENT 'CÓDIGO',
  `CAMFICAMET` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'MÉTODO',
  `CAMFICAUSU` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
  `CAMFICAFEC` datetime NOT NULL COMMENT 'FECHA HORA',
  `CAMFICADIP` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP',
  `CAMFICACODOLD` mediumint(9) NULL COMMENT 'CÓDIGO OLD',
  `CAMFICAESTOLD` mediumint(9) NULL COMMENT 'ESTADO OLD',
  `CAMFICANOMOLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CAMPAÑA OLD',
  `CAMFICAFDEOLD` date NULL COMMENT 'FECHA INICIO OLD',
  `CAMFICAFHAOLD` date NULL COMMENT 'FECHA FINAL OLD',
  `CAMFICACOLOLD` char(10) COLLATE utf8_spanish_ci NULL COMMENT 'FORMULARIO COLOR OLD',
  `CAMFICAFO1OLD` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'FORMULARIO 1 OLD',
  `CAMFICAFO2OLD` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'FORMULARIO 2 OLD',
  `CAMFICAFO3OLD` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'FORMULARIO 3 OLD',
  `CAMFICAFO4OLD` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'FORMULARIO 4 OLD',
  `CAMFICAFO5OLD` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'FORMULARIO 5 OLD',
  `CAMFICAFO6OLD` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'FORMULARIO 6 OLD',
  `CAMFICAFO7OLD` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'FORMULARIO 7 OLD',
  `CAMFICAFO8OLD` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'FORMULARIO 8 OLD',
  `CAMFICAOBSOLD` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN OLD',
  `CAMFICACODNEW` mediumint(9) NULL COMMENT 'CÓDIGO NEW',
  `CAMFICAESTNEW` mediumint(9) NULL COMMENT 'ESTADO NEW',
  `CAMFICANOMNEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CAMPAÑA NEW',
  `CAMFICAFDENEW` date NULL COMMENT 'FECHA INICIO NEW',
  `CAMFICAFHANEW` date NULL COMMENT 'FECHA FINAL NEW',
  `CAMFICACOLNEW` char(10) COLLATE utf8_spanish_ci NULL COMMENT 'FORMULARIO COLOR NEW',
  `CAMFICAFO1NEW` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'FORMULARIO 1 NEW',
  `CAMFICAFO2NEW` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'FORMULARIO 2 NEW',
  `CAMFICAFO3NEW` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'FORMULARIO 3 NEW',
  `CAMFICAFO4NEW` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'FORMULARIO 4 NEW',
  `CAMFICAFO5NEW` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'FORMULARIO 5 NEW',
  `CAMFICAFO6NEW` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'FORMULARIO 6 NEW',
  `CAMFICAFO7NEW` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'FORMULARIO 7 NEW',
  `CAMFICAFO8NEW` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'FORMULARIO 8 NEW',
  `CAMFICAOBSNEW` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN NEW'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='CAMPAÑA AUDITORÍA';

CREATE TRIGGER `CAMFICDLT` BEFORE DELETE ON `CAMFIC`
  FOR EACH ROW 
    INSERT INTO `CAMFICA` (`CAMFICAMET`, `CAMFICAUSU`, `CAMFICAFEC`, `CAMFICADIP`, `CAMFICACODOLD`, `CAMFICAESTOLD`, `CAMFICANOMOLD`, `CAMFICAFDEOLD`, `CAMFICAFHAOLD`, `CAMFICACOLOLD`, `CAMFICAFO1OLD`, `CAMFICAFO2OLD`, `CAMFICAFO3OLD`, `CAMFICAFO4OLD`, `CAMFICAFO5OLD`, `CAMFICAFO6OLD`, `CAMFICAFO7OLD`, `CAMFICAFO8OLD`, `CAMFICAOBSOLD`) 
    VALUES ('DELETE', OLD.`CAMFICAUS`, NOW(), OLD.`CAMFICAIP`, OLD.`CAMFICCOD`, OLD.`CAMFICEST`, OLD.`CAMFICNOM`, OLD.`CAMFICFDE`, OLD.`CAMFICFHA`, OLD.`CAMFICCOL`, OLD.`CAMFICFO1`, OLD.`CAMFICFO2`, OLD.`CAMFICFO3`, OLD.`CAMFICFO4`, OLD.`CAMFICFO5`, OLD.`CAMFICFO6`, OLD.`CAMFICFO7`, OLD.`CAMFICFO8`, OLD.`CAMFICOBS`);

CREATE TRIGGER `CAMFICINS` AFTER INSERT ON `CAMFIC`
  FOR EACH ROW 
    INSERT INTO `CAMFICA` (`CAMFICAMET`, `CAMFICAUSU`, `CAMFICAFEC`, `CAMFICADIP`, `CAMFICACODNEW`, `CAMFICAESTNEW`, `CAMFICANOMNEW`, `CAMFICAFDENEW`, `CAMFICAFHANEW`, `CAMFICACOLNEW`, `CAMFICAFO1NEW`, `CAMFICAFO2NEW`, `CAMFICAFO3NEW`, `CAMFICAFO4NEW`, `CAMFICAFO5NEW`, `CAMFICAFO6NEW`, `CAMFICAFO7NEW`, `CAMFICAFO8NEW`, `CAMFICAOBSNEW`) 
    VALUES ('INSERT', NEW.`CAMFICAUS`, NOW(), NEW.`CAMFICAIP`, NEW.`CAMFICCOD`, NEW.`CAMFICEST`, NEW.`CAMFICNOM`, NEW.`CAMFICFDE`, NEW.`CAMFICFHA`, NEW.`CAMFICCOL`, NEW.`CAMFICFO1`, NEW.`CAMFICFO2`, NEW.`CAMFICFO3`, NEW.`CAMFICFO4`, NEW.`CAMFICFO5`, NEW.`CAMFICFO6`, NEW.`CAMFICFO7`, NEW.`CAMFICFO8`, NEW.`CAMFICOBS`);

CREATE TRIGGER `CAMFICUPD` AFTER UPDATE ON `CAMFIC`
  FOR EACH ROW 
    INSERT INTO `CAMFICA` (`CAMFICAMET`, `CAMFICAUSU`, `CAMFICAFEC`, `CAMFICADIP`, `CAMFICACODOLD`, `CAMFICAESTOLD`, `CAMFICANOMOLD`, `CAMFICAFDEOLD`, `CAMFICAFHAOLD`, `CAMFICACOLOLD`, `CAMFICAFO1OLD`, `CAMFICAFO2OLD`, `CAMFICAFO3OLD`, `CAMFICAFO4OLD`, `CAMFICAFO5OLD`, `CAMFICAFO6OLD`, `CAMFICAFO7OLD`, `CAMFICAFO8OLD`, `CAMFICAOBSOLD`, `CAMFICACODNEW`, `CAMFICAESTNEW`, `CAMFICANOMNEW`, `CAMFICAFDENEW`, `CAMFICAFHANEW`, `CAMFICACOLNEW`, `CAMFICAFO1NEW`, `CAMFICAFO2NEW`, `CAMFICAFO3NEW`, `CAMFICAFO4NEW`, `CAMFICAFO5NEW`, `CAMFICAFO6NEW`, `CAMFICAFO7NEW`, `CAMFICAFO8NEW`, `CAMFICAOBSNEW`) 
    VALUES ('UPDATE', NEW.`CAMFICAUS`, NOW(), NEW.`CAMFICAIP`, OLD.`CAMFICCOD`, OLD.`CAMFICEST`, OLD.`CAMFICNOM`, OLD.`CAMFICFDE`, OLD.`CAMFICFHA`, OLD.`CAMFICCOL`, OLD.`CAMFICFO1`, OLD.`CAMFICFO2`, OLD.`CAMFICFO3`, OLD.`CAMFICFO4`, OLD.`CAMFICFO5`, OLD.`CAMFICFO6`, OLD.`CAMFICFO7`, OLD.`CAMFICFO8`, OLD.`CAMFICOBS`, NEW.`CAMFICCOD`, NEW.`CAMFICEST`, NEW.`CAMFICNOM`, NEW.`CAMFICFDE`, NEW.`CAMFICFHA`, NEW.`CAMFICCOL`, NEW.`CAMFICFO1`, NEW.`CAMFICFO2`, NEW.`CAMFICFO3`, NEW.`CAMFICFO4`, NEW.`CAMFICFO5`, NEW.`CAMFICFO6`, NEW.`CAMFICFO7`, NEW.`CAMFICFO8`, NEW.`CAMFICOBS`);

CREATE EVENT IF NOT EXISTS `CAMPANHA_ACTIVA` 
  ON SCHEDULE EVERY 1 DAY STARTS '2019-09-26 00:00:00.000000'
  ON COMPLETION NOT PRESERVE ENABLE 
  DO
    UPDATE `CAMFIC` SET `CAMFIC`.`CAMFICEST` = 4, `CAMFIC`.`CAMFICAUS` = 'SISTEMA', `CAMFIC`.`CAMFICAFH` = NOW(), `CAMFIC`.`CAMFICAIP` = '192.168.16.92' 
    WHERE `CAMFIC`.`CAMFICEST` = 3 AND `CAMFIC`.`CAMFICFDE` = NOW();

CREATE EVENT IF NOT EXISTS `CAMPANHA_FINALIZA` 
  ON SCHEDULE EVERY 1 DAY STARTS '2019-09-26 00:00:00.000000'
  ON COMPLETION NOT PRESERVE ENABLE 
  DO
    UPDATE `CAMFIC` SET `CAMFIC`.`CAMFICEST` = 5, `CAMFIC`.`CAMFICAUS` = 'SISTEMA', `CAMFIC`.`CAMFICAFH` = NOW(), `CAMFIC`.`CAMFICAIP` = '192.168.16.92' 
    WHERE `CAMFIC`.`CAMFICEST` = 4 AND `CAMFIC`.`CAMFICFHA` < NOW();

ALTER TABLE `CAMFIC` ADD PRIMARY KEY (`CAMFICCOD`);
ALTER TABLE `CAMFIC` MODIFY `CAMFICCOD` mediumint(9) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;
ALTER TABLE `CAMFIC` ADD KEY `CAMFICEST` (`CAMFICEST`);
ALTER TABLE `CAMFIC` ADD CONSTRAINT `FK_CAMFIC_CAMFICEST` FOREIGN KEY (`CAMFICEST`) REFERENCES `DOMFIC` (`DOMFICCOD`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `CAMFICA` ADD PRIMARY KEY (`CAMFICACOD`);
ALTER TABLE `CAMFICA` MODIFY `CAMFICACOD` int(11) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;