CREATE TABLE IF NOT EXISTS `FUNACA` (
    `FUNACACOD` mediumint(9) NOT NULL COMMENT 'CÓDIGO',
    `FUNACAEST` char(1) COLLATE utf8_spanish_ci NOT NULL COMMENT 'ESTADO',
    `FUNACATUC` mediumint(9) NOT NULL COMMENT 'UNIVERSIDAD',
    `FUNACATCC` mediumint(9) NOT NULL COMMENT 'CARRERA',
    `FUNACATGC` mediumint(9) NOT NULL COMMENT 'GRADO ACADEMICO',
    `FUNACATEC` mediumint(9) NOT NULL COMMENT 'ESTADO ACADEMICO',
    `FUNACAFUC` mediumint(9) NOT NULL COMMENT 'FUNCIONARIO',
    `FUNACAOBS` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN',
    `FUNACAAUS` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
    `FUNACAAFH` datetime NOT NULL COMMENT 'FECHA HORA',
    `FUNACAAIP` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='FUNCIONARIO ACADEMICO';

CREATE TABLE IF NOT EXISTS `FUNACAA` (
    `FUNACAACOD` int(11) NOT NULL COMMENT 'CÓDIGO',
    `FUNACAAMET` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'MÉTODO',
    `FUNACAAUSU` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
    `FUNACAAFEC` datetime NOT NULL COMMENT 'FECHA HORA',
    `FUNACAADIP` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP',

    `FUNACAACODOLD` mediumint(9) NULL COMMENT 'CÓDIGO OLD',
    `FUNACAAESTOLD` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'ESTADO OLD',
    `FUNACAATUCOLD` mediumint(9) NULL COMMENT 'UNIVERSIDAD OLD',
    `FUNACAATCCOLD` mediumint(9) NULL COMMENT 'CARRERA OLD',
    `FUNACAATGCOLD` mediumint(9) NULL COMMENT 'GRADO ACADEMICO OLD',
    `FUNACAATECOLD` mediumint(9) NULL COMMENT 'ESTADO ACADEMICO OLD',
    `FUNACAAFUCOLD` mediumint(9) NULL COMMENT 'FUNCIONARIO OLD',
    `FUNACAAOBSOLD` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN OLD',

    `FUNACAACODNEW` mediumint(9) NULL COMMENT 'CÓDIGO NEW',
    `FUNACAAESTNEW` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'ESTADO NEW',
    `FUNACAATUCNEW` mediumint(9) NULL COMMENT 'UNIVERSIDAD NEW',
    `FUNACAATCCNEW` mediumint(9) NULL COMMENT 'CARRERA NEW',
    `FUNACAATGCNEW` mediumint(9) NULL COMMENT 'GRADO ACADEMICO NEW',
    `FUNACAATECNEW` mediumint(9) NULL COMMENT 'ESTADO ACADEMICO NEW',
    `FUNACAAFUCNEW` mediumint(9) NULL COMMENT 'FUNCIONARIO NEW',
    `FUNACAAOBSNEW` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN NEW'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='FUNCIONARIO ACADEMICO AUDITORÍA';

CREATE TRIGGER `FUNACADLT` BEFORE DELETE ON `FUNACA`
    FOR EACH ROW 
        INSERT INTO `FUNACAA` (`FUNACAAMET`, `FUNACAAUSU`, `FUNACAAFEC`, `FUNACAADIP`, `FUNACAACODOLD`, `FUNACAAESTOLD`, `FUNACAATUCOLD`, `FUNACAATCCOLD`, `FUNACAATGCOLD`, `FUNACAATECOLD`, `FUNACAAFUCOLD`, `FUNACAAOBSOLD`)
        VALUES ('DELETE', OLD.`FUNACAAUS`, NOW(), OLD.`FUNACAAIP`, OLD.`FUNACACOD`, OLD.`FUNACAEST`, OLD.`FUNACATUC`, OLD.`FUNACATCC`, OLD.`FUNACATGC`, OLD.`FUNACATEC`, OLD.`FUNACAFUC`, OLD.`FUNACAOBS`);

CREATE TRIGGER `FUNACAINS` AFTER INSERT ON `FUNACA`
    FOR EACH ROW 
        INSERT INTO `FUNACAA` (`FUNACAAMET`, `FUNACAAUSU`, `FUNACAAFEC`, `FUNACAADIP`, `FUNACAACODNEW`, `FUNACAAESTNEW`, `FUNACAATUCNEW`, `FUNACAATCCNEW`, `FUNACAATGCNEW`, `FUNACAATECNEW`, `FUNACAAFUCNEW`, `FUNACAAOBSNEW`)
        VALUES ('INSERT', NEW.`FUNACAAUS`, NOW(), NEW.`FUNACAAIP`, NEW.`FUNACACOD`, NEW.`FUNACAEST`, NEW.`FUNACATUC`, NEW.`FUNACATCC`, NEW.`FUNACATGC`, NEW.`FUNACATEC`, NEW.`FUNACAFUC`, NEW.`FUNACAOBS`);

CREATE TRIGGER `FUNACAUPD` AFTER UPDATE ON `FUNACA`
    FOR EACH ROW 
        INSERT INTO `FUNACAA` (`FUNACAAMET`, `FUNACAAUSU`, `FUNACAAFEC`, `FUNACAADIP`, `FUNACAACODOLD`, `FUNACAAESTOLD`, `FUNACAATUCOLD`, `FUNACAATCCOLD`, `FUNACAATGCOLD`, `FUNACAATECOLD`, `FUNACAAFUCOLD`, `FUNACAAOBSOLD`, `FUNACAACODNEW`, `FUNACAAESTNEW`, `FUNACAATUCNEW`, `FUNACAATCCNEW`, `FUNACAATGCNEW`, `FUNACAATECNEW`, `FUNACAAFUCNEW`, `FUNACAAOBSNEW`)
        VALUES ('UPDATE', NEW.`FUNACAAUS`, NOW(), NEW.`FUNACAAIP`, OLD.`FUNACACOD`, OLD.`FUNACAEST`, OLD.`FUNACATUC`, OLD.`FUNACATCC`, OLD.`FUNACATGC`, OLD.`FUNACATEC`, OLD.`FUNACAFUC`, OLD.`FUNACAOBS`, NEW.`FUNACACOD`, NEW.`FUNACAEST`, NEW.`FUNACATUC`, NEW.`FUNACATCC`, NEW.`FUNACATGC`, NEW.`FUNACATEC`, NEW.`FUNACAFUC`, NEW.`FUNACAOBS`);


ALTER TABLE `FUNACA` ADD PRIMARY KEY (`FUNACACOD`);
ALTER TABLE `FUNACA` MODIFY `FUNACACOD` mediumint(9) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;

ALTER TABLE `FUNACA` ADD KEY `FUNACATUC` (`FUNACATUC`);
ALTER TABLE `FUNACA` ADD CONSTRAINT `FK_FUNACA_FUNACATUC` FOREIGN KEY (`FUNACATUC`) REFERENCES `DOMFIC` (`DOMFICCOD`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `FUNACA` ADD KEY `FUNACATCC` (`FUNACATCC`);
ALTER TABLE `FUNACA` ADD CONSTRAINT `FK_FUNACA_FUNACATCC` FOREIGN KEY (`FUNACATCC`) REFERENCES `DOMFIC` (`DOMFICCOD`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `FUNACA` ADD KEY `FUNACATGC` (`FUNACATGC`);
ALTER TABLE `FUNACA` ADD CONSTRAINT `FK_FUNACA_FUNACATGC` FOREIGN KEY (`FUNACATGC`) REFERENCES `DOMFIC` (`DOMFICCOD`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `FUNACA` ADD KEY `FUNACATEC` (`FUNACATEC`);
ALTER TABLE `FUNACA` ADD CONSTRAINT `FK_FUNACA_FUNACATEC` FOREIGN KEY (`FUNACATEC`) REFERENCES `DOMFIC` (`DOMFICCOD`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `FUNACA` ADD KEY `FUNACAFUC` (`FUNACAFUC`);
ALTER TABLE `FUNACA` ADD CONSTRAINT `FK_FUNACA_FUNACAFUC` FOREIGN KEY (`FUNACAFUC`) REFERENCES `FUNFIC` (`FUNFICCOD`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `FUNACAA` ADD PRIMARY KEY (`FUNACAACOD`);
ALTER TABLE `FUNACAA` MODIFY `FUNACAACOD` int(11) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;