CREATE TABLE IF NOT EXISTS `FUNCON` (
    `FUNCONCOD` mediumint(9) NOT NULL COMMENT 'CÓDIGO',
    `FUNCONEST` char(1) COLLATE utf8_spanish_ci NOT NULL COMMENT 'ESTADO',
    `FUNCONTSC` mediumint(9) NOT NULL COMMENT 'TIPO SEXO',
    `FUNCONFUC` mediumint(9) NOT NULL COMMENT 'FUNCIONARIO',
    `FUNCONNOM` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'NOMBRE',
    `FUNCONAPE` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'APELLIDO',
    `FUNCONFHA` date NULL COMMENT 'FECHA NACIMIENTO',
    `FUNCONEMP` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'EMPRESA',
    `FUNCONOBS` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN',
    `FUNCONAUS` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
    `FUNCONAFH` datetime NOT NULL COMMENT 'FECHA HORA',
    `FUNCONAIP` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='FUNCIONARIO CÓNYUGE';

CREATE TABLE IF NOT EXISTS `FUNCONA` (
    `FUNCONACOD` int(11) NOT NULL COMMENT 'CÓDIGO',
    `FUNCONAMET` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'MÉTODO',
    `FUNCONAUSU` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
    `FUNCONAFEC` datetime NOT NULL COMMENT 'FECHA HORA',
    `FUNCONADIP` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP',

    `FUNCONACODOLD` mediumint(9) NULL COMMENT 'CÓDIGO OLD',
    `FUNCONAESTOLD` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'ESTADO OLD',
    `FUNCONATSCOLD` mediumint(9) NULL COMMENT 'TIPO SEXO OLD',
    `FUNCONAFUCOLD` mediumint(9) NULL COMMENT 'FUNCIONARIO OLD',
    `FUNCONANOMOLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'NOMBRE OLD',
    `FUNCONAAPEOLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'APELLIDO OLD',
    `FUNCONAFHAOLD` date NULL COMMENT 'FECHA NACIMIENTO OLD',
    `FUNCONAEMPOLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'EMPRESA OLD',
    `FUNCONAOBSOLD` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN OLD',

    `FUNCONACODNEW` mediumint(9) NULL COMMENT 'CÓDIGO NEW',
    `FUNCONAESTNEW` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'ESTADO NEW',
    `FUNCONATSCNEW` mediumint(9) NULL COMMENT 'TIPO SEXO NEW',
    `FUNCONAFUCNEW` mediumint(9) NULL COMMENT 'FUNCIONARIO NEW',
    `FUNCONANOMNEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'NOMBRE NEW',
    `FUNCONAAPENEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'APELLIDO NEW',
    `FUNCONAFHANEW` date NULL COMMENT 'FECHA NACIMIENTO NEW',
    `FUNCONAEMPNEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'EMPRESA NEW',
    `FUNCONAOBSNEW` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN NEW'

) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='FUNCIONARIO CÓNYUGE AUDITORÍA';

CREATE TRIGGER `FUNCONDLT` BEFORE DELETE ON `FUNCON`
    FOR EACH ROW 
        INSERT INTO `FUNCONA` (`FUNCONAMET`, `FUNCONAUSU`, `FUNCONAFEC`, `FUNCONADIP`, `FUNCONACODOLD`, `FUNCONAESTOLD`, `FUNCONATSCOLD`, `FUNCONAFUCOLD`, `FUNCONANOMOLD`, `FUNCONAAPEOLD`, `FUNCONAFHAOLD`, `FUNCONAEMPOLD`, `FUNCONAOBSOLD`) 
        VALUES ('DELETE', OLD.`FUNCONAUS`, NOW(), OLD.`FUNCONAIP`,  OLD.`FUNCONCOD`,  OLD.`FUNCONEST`,  OLD.`FUNCONTSC`,  OLD.`FUNCONFUC`,  OLD.`FUNCONNOM`,  OLD.`FUNCONAPE`,  OLD.`FUNCONFHA`,  OLD.`FUNCONEMP`,  OLD.`FUNCONOBS`);

CREATE TRIGGER `FUNCONINS` AFTER INSERT ON `FUNCON`
    FOR EACH ROW 
        INSERT INTO `FUNCONA` (`FUNCONAMET`, `FUNCONAUSU`, `FUNCONAFEC`, `FUNCONADIP`, `FUNCONACODNEW`, `FUNCONAESTNEW`, `FUNCONATSCNEW`, `FUNCONAFUCNEW`, `FUNCONANOMNEW`, `FUNCONAAPENEW`, `FUNCONAFHANEW`, `FUNCONAEMPNEW`, `FUNCONAOBSNEW`)
        VALUES ('INSERT', NEW.`FUNCONAUS`, NOW(), NEW.`FUNCONAIP`, NEW.`FUNCONCOD`,  NEW.`FUNCONEST`,  NEW.`FUNCONTSC`,  NEW.`FUNCONFUC`,  NEW.`FUNCONNOM`,  NEW.`FUNCONAPE`,  NEW.`FUNCONFHA`,  NEW.`FUNCONEMP`,  NEW.`FUNCONOBS`);

CREATE TRIGGER `FUNCONUPD` AFTER UPDATE ON `FUNCON`
    FOR EACH ROW 
        INSERT INTO `FUNCONA` (`FUNCONAMET`, `FUNCONAUSU`, `FUNCONAFEC`, `FUNCONADIP`, `FUNCONACODOLD`, `FUNCONAESTOLD`, `FUNCONATSCOLD`, `FUNCONAFUCOLD`, `FUNCONANOMOLD`, `FUNCONAAPEOLD`, `FUNCONAFHAOLD`, `FUNCONAEMPOLD`, `FUNCONAOBSOLD`, `FUNCONACODNEW`, `FUNCONAESTNEW`, `FUNCONATSCNEW`, `FUNCONAFUCNEW`, `FUNCONANOMNEW`, `FUNCONAAPENEW`, `FUNCONAFHANEW`, `FUNCONAEMPNEW`, `FUNCONAOBSNEW`) 
        VALUES ('UPDATE', NEW.`FUNCONAUS`, NOW(), NEW.`FUNCONAIP`, OLD.`FUNCONCOD`,  OLD.`FUNCONEST`,  OLD.`FUNCONTSC`,  OLD.`FUNCONFUC`,  OLD.`FUNCONNOM`,  OLD.`FUNCONAPE`,  OLD.`FUNCONFHA`,  OLD.`FUNCONEMP`,  OLD.`FUNCONOBS`, NEW.`FUNCONCOD`,  NEW.`FUNCONEST`,  NEW.`FUNCONTSC`,  NEW.`FUNCONFUC`,  NEW.`FUNCONNOM`,  NEW.`FUNCONAPE`,  NEW.`FUNCONFHA`,  NEW.`FUNCONEMP`,  NEW.`FUNCONOBS`);

ALTER TABLE `FUNCON` ADD PRIMARY KEY (`FUNCONCOD`);
ALTER TABLE `FUNCON` MODIFY `FUNCONCOD` mediumint(9) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;
ALTER TABLE `FUNCON` ADD KEY `FUNCONTSC` (`FUNCONTSC`);
ALTER TABLE `FUNCON` ADD KEY `FUNCONFUC` (`FUNCONFUC`);
ALTER TABLE `FUNCON` ADD CONSTRAINT `FK_FUNCON_FUNCONTSC` FOREIGN KEY (`FUNCONTSC`) REFERENCES `DOMFIC` (`DOMFICCOD`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `FUNCON` ADD CONSTRAINT `FK_FUNCON_FUNCONFUC` FOREIGN KEY (`FUNCONFUC`) REFERENCES `FUNFIC` (`FUNFICCOD`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `FUNCONA` ADD PRIMARY KEY (`FUNCONACOD`);
ALTER TABLE `FUNCONA` MODIFY `FUNCONACOD` int(11) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;