CREATE TABLE IF NOT EXISTS `LOCBAR` (
    `LOCBARCOD` mediumint(9) NOT NULL COMMENT 'CÓDIGO',
    `LOCBAREST` char(1) COLLATE utf8_spanish_ci NOT NULL COMMENT 'ESTADO',
    `LOCBARCIC` mediumint(9) NOT NULL COMMENT 'CIUDAD',
    `LOCBARNOM` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'NOMBRE',
    `LOCBAREQU` int(15) NULL COMMENT 'CÓDIGO EQUIVALENCIA',
    `LOCBAROBS` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN',
    `LOCBARAUS` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
    `LOCBARAFH` datetime NOT NULL COMMENT 'FECHA HORA',
    `LOCBARAIP` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='LOCALIDAD BARRIO';

CREATE TABLE IF NOT EXISTS `LOCBARA` (
    `LOCBARACOD` int(11) NOT NULL COMMENT 'CÓDIGO',
    `LOCBARAMET` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'MÉTODO',
    `LOCBARAUSU` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
    `LOCBARAFEC` datetime NOT NULL COMMENT 'FECHA HORA',
    `LOCBARADIP` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP',

    `LOCBARACODOLD` mediumint(9) NULL COMMENT 'CÓDIGO OLD',
    `LOCBARAESTOLD` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'ESTADO OLD',
    `LOCBARACICOLD` mediumint(9) NULL COMMENT 'CIUDAD OLD',
    `LOCBARANOMOLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'NOMBRE OLD',
    `LOCBARAEQUOLD` int(15) NULL COMMENT 'CÓDIGO EQUIVALENCIA OLD',
    `LOCBARAOBSOLD` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN OLD',

    `LOCBARACODNEW` mediumint(9) NULL COMMENT 'CÓDIGO NEW',
    `LOCBARAESTNEW` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'ESTADO NEW',
    `LOCBARACICNEW` mediumint(9) NULL COMMENT 'CIUDAD NEW',
    `LOCBARANOMNEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'NOMBRE NEW',
    `LOCBARAEQUNEW` int(15) NULL COMMENT 'CÓDIGO EQUIVALENCIA NEW',
    `LOCBARAOBSNEW` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN NEW'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='LOCALIDAD BARRIO AUDITORÍA';

CREATE TRIGGER `LOCBARDLT` BEFORE DELETE ON `LOCBAR`
    FOR EACH ROW 
        INSERT INTO `LOCBARA` (`LOCBARAMET`, `LOCBARAUSU`, `LOCBARAFEC`, `LOCBARADIP`, `LOCBARACODOLD`, `LOCBARAESTOLD`, `LOCBARACICOLD`, `LOCBARANOMOLD`, `LOCBARAEQUOLD`, `LOCBARAOBSOLD`)
        VALUES ('DELETE', OLD.`LOCBARAUS`, NOW(), OLD.`LOCBARAIP`, OLD.`LOCBARCOD`, OLD.`LOCBAREST`, OLD.`LOCBARCIC`, OLD.`LOCBARNOM`, OLD.`LOCBAREQU`, OLD.`LOCBAROBS`);

CREATE TRIGGER `LOCBARINS` AFTER INSERT ON `LOCBAR`
    FOR EACH ROW 
        INSERT INTO `LOCBARA` (`LOCBARAMET`, `LOCBARAUSU`, `LOCBARAFEC`, `LOCBARADIP`, `LOCBARACODNEW`, `LOCBARAESTNEW`, `LOCBARACICNEW`, `LOCBARANOMNEW`, `LOCBARAEQUNEW`, `LOCBARAOBSNEW`)
        VALUES ('INSERT', NEW.`LOCBARAUS`, NOW(), NEW.`LOCBARAIP`, NEW.`LOCBARCOD`, NEW.`LOCBAREST`, NEW.`LOCBARCIC`, NEW.`LOCBARNOM`, NEW.`LOCBAREQU`, NEW.`LOCBAROBS`);

CREATE TRIGGER `LOCBARUPD` AFTER UPDATE ON `LOCBAR`
    FOR EACH ROW 
        INSERT INTO `LOCBARA` (`LOCBARAMET`, `LOCBARAUSU`, `LOCBARAFEC`, `LOCBARADIP`, `LOCBARACODOLD`, `LOCBARAESTOLD`, `LOCBARACICOLD`, `LOCBARANOMOLD`, `LOCBARAEQUOLD`, `LOCBARAOBSOLD`, `LOCBARACODNEW`, `LOCBARAESTNEW`, `LOCBARACICNEW`, `LOCBARANOMNEW`, `LOCBARAEQUNEW`, `LOCBARAOBSNEW`)
        VALUES ('UPDATE', NEW.`LOCBARAUS`, NOW(), NEW.`LOCBARAIP`, OLD.`LOCBARCOD`, OLD.`LOCBAREST`, OLD.`LOCBARCIC`, OLD.`LOCBARNOM`, OLD.`LOCBAREQU`, OLD.`LOCBAROBS`, NEW.`LOCBARCOD`, NEW.`LOCBAREST`, NEW.`LOCBARCIC`, NEW.`LOCBARNOM`, NEW.`LOCBAREQU`, NEW.`LOCBAROBS`);

ALTER TABLE `LOCBAR` ADD PRIMARY KEY (`LOCBARCOD`);
ALTER TABLE `LOCBAR` MODIFY `LOCBARCOD` mediumint(9) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;

ALTER TABLE `LOCBAR` ADD KEY `LOCBARCIC` (`LOCBARCIC`);
ALTER TABLE `LOCBAR` ADD CONSTRAINT `FK_LOCBAR_LOCBARCIC` FOREIGN KEY (`LOCBARCIC`) REFERENCES `LOCCIU` (`LOCCIUCOD`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `LOCBARA` ADD PRIMARY KEY (`LOCBARACOD`);
ALTER TABLE `LOCBARA` MODIFY `LOCBARACOD` int(11) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;