CREATE TABLE `CAMFIC` (
    `CAMFICCOD` mediumint(9) NOT NULL COMMENT 'CÓDIGO',
    `CAMFICEST` char(1) COLLATE utf8_spanish_ci NOT NULL COMMENT 'ESTADO',
    `CAMFICNOM` varchar(100) COLLATE utf8_spanish_ci NOT NULL COMMENT 'CAMPAÑA',
    `CAMFICFDE` datetime NOT NULL COMMENT 'FECHA INICIO',
    `CAMFICFHA` datetime NOT NULL COMMENT 'FECHA FINAL',
    `CAMFICOBS` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN',
    `CAMFICAUS` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
    `CAMFICAFH` datetime NOT NULL COMMENT 'FECHA HORA',
    `CAMFICAIP` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='CAMPAÑA';

CREATE TABLE `CAMFICA` (
    `CAMFICACOD` int(11) NOT NULL COMMENT 'CÓDIGO',
    `CAMFICAMET` char(20) COLLATE utf8_spanish_ci NULL COMMENT 'MÉTODO',
    `CAMFICAUSU` char(20) COLLATE utf8_spanish_ci NULL COMMENT 'USUARIO',
    `CAMFICAFEC` datetime DEFAULT NULL COMMENT 'FECHA HORA',
    `CAMFICADIP` char(20) COLLATE utf8_spanish_ci NULL COMMENT 'IP',
    `CAMFICACODOLD` mediumint(9) NOT NULL COMMENT 'CÓDIGO OLD',
    `CAMFICAESTOLD` char(1) COLLATE utf8_spanish_ci NOT NULL COMMENT 'ESTADO OLD',
    `CAMFICANOMOLD` varchar(100) COLLATE utf8_spanish_ci NOT NULL COMMENT 'CAMPAÑA OLD',
    `CAMFICAFDEOLD` datetime NOT NULL COMMENT 'FECHA INICIO OLD',
    `CAMFICAFHAOLD` datetime NOT NULL COMMENT 'FECHA FINAL OLD',
    `CAMFICAOBSOLD` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN OLD',
    `CAMFICACODNEW` mediumint(9) NOT NULL COMMENT 'CÓDIGO NEW',
    `CAMFICAESTNEW` char(1) COLLATE utf8_spanish_ci NOT NULL COMMENT 'ESTADO NEW',
    `CAMFICANOMNEW` varchar(100) COLLATE utf8_spanish_ci NOT NULL COMMENT 'CAMPAÑA NEW',
    `CAMFICAFDENEW` datetime NOT NULL COMMENT 'FECHA INICIO NEW',
    `CAMFICAFHANEW` datetime NOT NULL COMMENT 'FECHA FINAL NEW',
    `CAMFICAOBSNEW` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN NEW'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='CAMPAÑA AUDITORÍA';

ALTER TABLE `CAMFIC` ADD PRIMARY KEY (`CAMFICCOD`);
ALTER TABLE `CAMFIC` MODIFY `CAMFICCOD` mediumint(9) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;
ALTER TABLE `CAMFICA` ADD PRIMARY KEY (`CAMFICACOD`);
ALTER TABLE `CAMFICA` MODIFY `CAMFICACOD` int(11) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;

CREATE TRIGGER `CAMFICDLT` BEFORE DELETE ON `CAMFIC`
  FOR EACH ROW 
    INSERT INTO `CAMFICA` (`CAMFICAMET`, `CAMFICAUSU`, `CAMFICAFEC`, `CAMFICADIP`, `CAMFICACODOLD`, `CAMFICAESTOLD`, `CAMFICANOMOLD`, `CAMFICAFDEOLD`, `CAMFICAFHAOLD`, `CAMFICAOBSOLD`) 
    VALUES ('DELETE', OLD.`CAMFICAUS`, OLD.`CAMFICAFH`, OLD.`CAMFICAIP`, OLD.`CAMFICCOD`, OLD.`CAMFICEST`, OLD.`CAMFICNOM`, OLD.`CAMFICFDE`, OLD.`CAMFICFHA`, OLD.`CAMFICOBS`);

CREATE TRIGGER `CAMFICINS` AFTER INSERT ON `CAMFIC`
  FOR EACH ROW 
    INSERT INTO `CAMFICA` (`CAMFICAMET`, `CAMFICAUSU`, `CAMFICAFEC`, `CAMFICADIP`, `CAMFICACODNEW`, `CAMFICAESTNEW`, `CAMFICANOMNEW`, `CAMFICAFDENEW`, `CAMFICAFHANEW`, `CAMFICAOBSNEW`) 
    VALUES ('INSERT', NEW.`CAMFICAUS`, NEW.`CAMFICAFH`, NEW.`CAMFICAIP`, NEW.`CAMFICCOD`, NEW.`CAMFICEST`, NEW.`CAMFICNOM`, NEW.`CAMFICFDE`, NEW.`CAMFICFHA`, NEW.`CAMFICOBS`);

CREATE TRIGGER `CAMFICUPD` AFTER UPDATE ON `CAMFIC`
  FOR EACH ROW 
    INSERT INTO `CAMFICA` (`CAMFICAMET`, `CAMFICAUSU`, `CAMFICAFEC`, `CAMFICADIP`, `CAMFICACODOLD`, `CAMFICAESTOLD`, `CAMFICANOMOLD`, `CAMFICAFDEOLD`, `CAMFICAFHAOLD`, `CAMFICAOBSOLD`, `CAMFICACODNEW`, `CAMFICAESTNEW`, `CAMFICANOMNEW`, `CAMFICAFDENEW`, `CAMFICAFHANEW`, `CAMFICAOBSNEW`) 
    VALUES ('INSERT', NEW.`CAMFICAUS`, NEW.`CAMFICAFH`, NEW.`CAMFICAIP`, OLD.`CAMFICCOD`, OLD.`CAMFICEST`, OLD.`CAMFICNOM`, OLD.`CAMFICFDE`, OLD.`CAMFICFHA`, OLD.`CAMFICOBS`, NEW.`CAMFICCOD`, NEW.`CAMFICEST`, NEW.`CAMFICNOM`, NEW.`CAMFICFDE`, NEW.`CAMFICFHA`, NEW.`CAMFICOBS`);