CREATE TABLE `DOMFIC` (
  `DOMFICCOD` mediumint(9) NOT NULL COMMENT 'CÓDIGO',
  `DOMFICEST` char(1) COLLATE utf8_spanish_ci NOT NULL COMMENT 'ESTADO',
  `DOMFICNOM` varchar(100) COLLATE utf8_spanish_ci NOT NULL COMMENT 'NOMBRE',
  `DOMFICEQU` char(20) COLLATE utf8_spanish_ci NULL COMMENT 'CÓDIGO EQUIVALENTE',
  `DOMFICVAL` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'DOMINIO',
  `DOMFICOBS` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN',
  `DOMFICAUS` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
  `DOMFICAFH` datetime NOT NULL COMMENT 'FECHA HORA',
  `DOMFICAIP` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='DOMINIO';

CREATE TABLE `DOMFICA` (
  `DOMFICACOD` int(11) NOT NULL COMMENT 'CÓDIGO',
  `DOMFICAMET` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'MÉTODO',
  `DOMFICAUSU` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
  `DOMFICAFEC` datetime NOT NULL COMMENT 'FECHA HORA',
  `DOMFICADIP` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP',
  `DOMFICACODOLD` mediumint(9) DEFAULT NULL COMMENT 'CÓDIGO ANTERIOR',
  `DOMFICAESTOLD` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'ESTADO ANTERIOR',
  `DOMFICANOMOLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'NOMBRE ANTERIOR',
  `DOMFICAEQUOLD` char(20) COLLATE utf8_spanish_ci NULL COMMENT 'CÓDIGO EQUIVALENTE ANTERIOR',
  `DOMFICAVALOLD` char(20) COLLATE utf8_spanish_ci NULL COMMENT 'DOMINIO ANTERIOR',
  `DOMFICAOBSOLD` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN ANTERIOR',
  `DOMFICACODNEW` mediumint(9) DEFAULT NULL COMMENT 'CÓDIGO ACTUAL',
  `DOMFICAESTNEW` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'ESTADO ACTUAL',
  `DOMFICANOMNEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'NOMBRE ACTUAL',
  `DOMFICAEQUNEW` char(20) COLLATE utf8_spanish_ci NULL COMMENT 'CÓDIGO EQUIVALENTE ACTUAL',
  `DOMFICAVALNEW` char(20) COLLATE utf8_spanish_ci NULL COMMENT 'DOMINIO ACTUAL',
  `DOMFICAOBSNEW` varchar(5120) COLLATE utf8_spanish_ci NULL COMMENT 'OBSERVACIÓN ACTUAL'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='DOMINIO AUDITORÍA';

ALTER TABLE `DOMFIC` ADD PRIMARY KEY (`DOMFICCOD`);
ALTER TABLE `DOMFIC` MODIFY `DOMFICCOD` mediumint(9) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=0;
ALTER TABLE `DOMFICA` ADD PRIMARY KEY (`DOMFICACOD`);
ALTER TABLE `DOMFICA` MODIFY `DOMFICACOD` int(11) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;

CREATE TRIGGER `DOMFICDLT` BEFORE DELETE ON `DOMFIC`
  FOR EACH ROW 
    INSERT INTO `DOMFICA` (`DOMFICAMET`, `DOMFICAUSU`, `DOMFICAFEC`, `DOMFICADIP`, `DOMFICACODOLD`, `DOMFICAESTOLD`, `DOMFICANOMOLD`, `DOMFICAEQUOLD`, `DOMFICAVALOLD`, `DOMFICAOBSOLD`) 
    VALUES ('DELETE', OLD.`DOMFICAUS`, OLD.`DOMFICAFH`, OLD.`DOMFICAIP`, OLD.`DOMFICCOD`, OLD.`DOMFICEST`, OLD.`DOMFICNOM`, OLD.`DOMFICEQU`, OLD.`DOMFICVAL`, OLD.`DOMFICOBS`);

CREATE TRIGGER `DOMFICINS` AFTER INSERT ON `DOMFIC`
  FOR EACH ROW 
    INSERT INTO `DOMFICA` (`DOMFICAMET`, `DOMFICAUSU`, `DOMFICAFEC`, `DOMFICADIP`, `DOMFICACODNEW`, `DOMFICAESTNEW`, `DOMFICANOMNEW`, `DOMFICAEQUNEW`, `DOMFICAVALNEW`, `DOMFICAOBSNEW`) 
    VALUES ('INSERT', NEW.`DOMFICAUS`, NEW.`DOMFICAFH`, NEW.`DOMFICAIP`, NEW.`DOMFICCOD`, NEW.`DOMFICEST`, NEW.`DOMFICNOM`, NEW.`DOMFICEQU`, NEW.`DOMFICVAL`, NEW.`DOMFICOBS`);

CREATE TRIGGER `DOMFICUPD` AFTER UPDATE ON `DOMFIC`
  FOR EACH ROW 
    INSERT INTO `DOMFICA` (`DOMFICAMET`, `DOMFICAUSU`, `DOMFICAFEC`, `DOMFICADIP`, `DOMFICACODOLD`, `DOMFICACODNEW`, `DOMFICAESTOLD`, `DOMFICAESTNEW`, `DOMFICANOMOLD`, `DOMFICANOMNEW`, `DOMFICAEQUOLD`, `DOMFICAEQUNEW`, `DOMFICAVALOLD`, `DOMFICAVALNEW`, `DOMFICAOBSOLD`, `DOMFICAOBSNEW`) 
    VALUES ('UPDATE', NEW.`DOMFICAUS`, NEW.`DOMFICAFH`, NEW.`DOMFICAIP`, OLD.`DOMFICCOD`, NEW.`DOMFICCOD`, OLD.`DOMFICEST`, NEW.`DOMFICEST`, OLD.`DOMFICNOM`, NEW.`DOMFICNOM`, OLD.`DOMFICEQU`, NEW.`DOMFICEQU`, OLD.`DOMFICVAL`, NEW.`DOMFICVAL`, OLD.`DOMFICOBS`, NEW.`DOMFICOBS`);