CREATE TABLE IF NOT EXISTS `FUNCEL` (
    `FUNCELCOD` mediumint(9) NOT NULL COMMENT 'CÓDIGO',
    `FUNCELEST` char(1) COLLATE utf8_spanish_ci NOT NULL COMMENT 'ESTADO',
    `FUNCELTMC` mediumint(9) NOT NULL COMMENT 'MARCA',
    `FUNCELTCC` mediumint(9) NOT NULL COMMENT 'COLOR',
    `FUNCELFUC` mediumint(9) NOT NULL COMMENT 'FUNCIONARIO',
    `FUNCELMOD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'MODELO',
    `FUNCELOBS` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN',
    `FUNCELAUS` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
    `FUNCELAFH` datetime NOT NULL COMMENT 'FECHA HORA',
    `FUNCELAIP` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='FUNCIONARIO CELULAR';

CREATE TABLE IF NOT EXISTS `FUNCELA` (
    `FUNCELACOD` int(11) NOT NULL COMMENT 'CÓDIGO',
    `FUNCELAMET` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'MÉTODO',
    `FUNCELAUSU` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
    `FUNCELAFEC` datetime NOT NULL COMMENT 'FECHA HORA',
    `FUNCELADIP` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP',

    `FUNCELACODOLD` mediumint(9) NULL COMMENT 'CÓDIGO OLD',
    `FUNCELAESTOLD` char(1) COLLATE utf8_spanish_ci NOT NULL COMMENT 'ESTADO OLD',
    `FUNCELATMCOLD` mediumint(9) NULL COMMENT 'MARCA OLD',
    `FUNCELATCCOLD` mediumint(9) NULL COMMENT 'COLOR OLD',
    `FUNCELAFUCOLD` mediumint(9) NULL COMMENT 'FUNCIONARIO OLD',
    `FUNCELAMODOLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'MODELO OLD',
    `FUNCELAOBSOLD` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN OLD',

    `FUNCELACODNEW` mediumint(9) NULL COMMENT 'CÓDIGO NEW',
    `FUNCELAESTNEW` char(1) COLLATE utf8_spanish_ci NOT NULL COMMENT 'ESTADO NEW',
    `FUNCELATMCNEW` mediumint(9) NULL COMMENT 'MARCA NEW',
    `FUNCELATCCNEW` mediumint(9) NULL COMMENT 'COLOR NEW',
    `FUNCELAFUCNEW` mediumint(9) NULL COMMENT 'FUNCIONARIO NEW',
    `FUNCELAMODNEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'MODELO NEW',
    `FUNCELAOBSNEW` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN NEW'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='FUNCIONARIO CELULAR AUDITORÍA';

CREATE TRIGGER `FUNCELDLT` BEFORE DELETE ON `FUNCEL`
    FOR EACH ROW 
        INSERT INTO `FUNCELA` (`FUNCELAMET`, `FUNCELAUSU`, `FUNCELAFEC`, `FUNCELADIP`, `FUNCELACODOLD`, `FUNCELAESTOLD`, `FUNCELATMCOLD`, `FUNCELATCCOLD`, `FUNCELAFUCOLD`, `FUNCELAMODOLD`, `FUNCELAOBSOLD`)
        VALUES ('DELETE', OLD.`FUNCELAUS`, NOW(), OLD.`FUNCELAIP`, OLD.`FUNCELCOD`, OLD.`FUNCELEST`, OLD.`FUNCELTMC`, OLD.`FUNCELTCC`, OLD.`FUNCELFUC`, OLD.`FUNCELMOD`, OLD.`FUNCELOBS`);

CREATE TRIGGER `FUNCELINS` AFTER INSERT ON `FUNCEL`
    FOR EACH ROW 
        INSERT INTO `FUNCELA` (`FUNCELAMET`, `FUNCELAUSU`, `FUNCELAFEC`, `FUNCELADIP`, `FUNCELACODNEW`, `FUNCELAESTNEW`, `FUNCELATMCNEW`, `FUNCELATCCNEW`, `FUNCELAFUCNEW`, `FUNCELAMODNEW`, `FUNCELAOBSNEW`)
        VALUES ('INSERT', NEW.`FUNCELAUS`, NOW(), NEW.`FUNCELAIP`, NEW.`FUNCELCOD`, NEW.`FUNCELEST`, NEW.`FUNCELTMC`, NEW.`FUNCELTCC`, NEW.`FUNCELFUC`, NEW.`FUNCELMOD`, NEW.`FUNCELOBS`);

CREATE TRIGGER `FUNCELUPD` AFTER UPDATE ON `FUNCEL`
    FOR EACH ROW 
        INSERT INTO `FUNCELA` (`FUNCELAMET`, `FUNCELAUSU`, `FUNCELAFEC`, `FUNCELADIP`, `FUNCELACODOLD`, `FUNCELAESTOLD`, `FUNCELATMCOLD`, `FUNCELATCCOLD`, `FUNCELAFUCOLD`, `FUNCELAMODOLD`, `FUNCELAOBSOLD`, `FUNCELACODNEW`, `FUNCELAESTNEW`, `FUNCELATMCNEW`, `FUNCELATCCNEW`, `FUNCELAFUCNEW`, `FUNCELAMODNEW`, `FUNCELAOBSNEW`)
        VALUES ('UPDATE', NEW.`FUNCELAUS`, NOW(), NEW.`FUNCELAIP`, OLD.`FUNCELCOD`, OLD.`FUNCELEST`, OLD.`FUNCELTMC`, OLD.`FUNCELTCC`, OLD.`FUNCELFUC`, OLD.`FUNCELMOD`, OLD.`FUNCELOBS`, NEW.`FUNCELCOD`, NEW.`FUNCELEST`, NEW.`FUNCELTMC`, NEW.`FUNCELTCC`, NEW.`FUNCELFUC`, NEW.`FUNCELMOD`, NEW.`FUNCELOBS`);


ALTER TABLE `FUNCEL` ADD PRIMARY KEY (`FUNCELCOD`);
ALTER TABLE `FUNCEL` MODIFY `FUNCELCOD` mediumint(9) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;

ALTER TABLE `FUNCEL` ADD KEY `FUNCELTMC` (`FUNCELTMC`);
ALTER TABLE `FUNCEL` ADD CONSTRAINT `FK_FUNCEL_FUNCELTMC` FOREIGN KEY (`FUNCELTMC`) REFERENCES `DOMFIC` (`DOMFICCOD`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `FUNCEL` ADD KEY `FUNCELTCC` (`FUNCELTCC`);
ALTER TABLE `FUNCEL` ADD CONSTRAINT `FK_FUNCEL_FUNCELTCC` FOREIGN KEY (`FUNCELTCC`) REFERENCES `DOMFIC` (`DOMFICCOD`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `FUNCEL` ADD KEY `FUNCELFUC` (`FUNCELFUC`);
ALTER TABLE `FUNCEL` ADD CONSTRAINT `FK_FUNCEL_FUNCELFUC` FOREIGN KEY (`FUNCELFUC`) REFERENCES `FUNFIC` (`FUNFICCOD`) ON DELETE RESTRICT ON UPDATE RESTRICT;