CREATE TABLE IF NOT EXISTS `FUNFIC` (
    `FUNFICCOD` mediumint(9) NOT NULL COMMENT 'CÓDIGO',
    `FUNFICEST` char(1) COLLATE utf8_spanish_ci NOT NULL COMMENT 'ESTADO',
    `FUNFICTDC` mediumint(9) NOT NULL COMMENT 'TIPO DOCUMENTO',
    `FUNFICTSC` mediumint(9) NOT NULL COMMENT 'TIPO SEXO',
    `FUNFICECC` mediumint(9) NOT NULL COMMENT 'ESTADO CIVIL',
    `FUNFICCFU` mediumint(9) NOT NULL COMMENT 'CÓDIGO FUNCIONARIO',
    `FUNFICNOM` varchar(100) COLLATE utf8_spanish_ci NOT NULL COMMENT 'NOMBRE',
    `FUNFICAPE` varchar(100) COLLATE utf8_spanish_ci NOT NULL COMMENT 'APELLIDO',
    `FUNFICDOC` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'DOCUMENTO',
    `FUNFICFHA` date NOT NULL COMMENT 'FECHA NACIMIENTO',
    `FUNFICEMA` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'EMAIL',
    `FUNFICOBS` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN',
    `FUNFICAUS` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
    `FUNFICAFH` datetime NOT NULL COMMENT 'FECHA HORA',
    `FUNFICAIP` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='FUNCIONARIO';

CREATE TABLE IF NOT EXISTS `FUNFICA` (
    `FUNFICACOD` int(11) NOT NULL COMMENT 'CÓDIGO',
    `FUNFICAMET` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'MÉTODO',
    `FUNFICAUSU` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
    `FUNFICAFEC` datetime NOT NULL COMMENT 'FECHA HORA',
    `FUNFICADIP` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP',
    `FUNFICACODOLD` mediumint(9) NULL COMMENT 'CÓDIGO OLD',
    `FUNFICAESTOLD` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'ESTADO OLD',
    `FUNFICATDCOLD` mediumint(9) NULL COMMENT 'TIPO DOCUMENTO OLD',
    `FUNFICATSCOLD` mediumint(9) NULL COMMENT 'TIPO SEXO OLD',
    `FUNFICAECCOLD` mediumint(9) NULL COMMENT 'ESTADO CIVIL OLD',
    `FUNFICACFUOLD` mediumint(9) NULL COMMENT 'CÓDIGO FUNCIONARIO OLD',
    `FUNFICANOMOLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'NOMBRE OLD',
    `FUNFICAAPEOLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'APELLIDO OLD',
    `FUNFICADOCOLD` char(20) COLLATE utf8_spanish_ci NULL COMMENT 'DOCUMENTO OLD',
    `FUNFICAFHAOLD` date NULL COMMENT 'FECHA NACIMIENTO OLD',
    `FUNFICAEMAOLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'EMAIL OLD',
    `FUNFICAOBSOLD` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN OLD',
    `FUNFICACODNEW` mediumint(9) NULL COMMENT 'CÓDIGO NEW',
    `FUNFICAESTNEW` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'ESTADO NEW',
    `FUNFICATDCNEW` mediumint(9) NULL COMMENT 'TIPO DOCUMENTO NEW',
    `FUNFICATSCNEW` mediumint(9) NULL COMMENT 'TIPO SEXO NEW',
    `FUNFICAECCNEW` mediumint(9) NULL COMMENT 'ESTADO CIVIL NEW',
    `FUNFICACFUNEW` mediumint(9) NULL COMMENT 'CÓDIGO FUNCIONARIO NEW',
    `FUNFICANOMNEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'NOMBRE NEW',
    `FUNFICAAPENEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'APELLIDO NEW',
    `FUNFICADOCNEW` char(20) COLLATE utf8_spanish_ci NULL COMMENT 'DOCUMENTO NEW',
    `FUNFICAFHANEW` date NULL COMMENT 'FECHA NACIMIENTO NEW',
    `FUNFICAEMANEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'EMAIL NEW',
    `FUNFICAOBSNEW` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN NEW'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='FUNCIONARIO AUDITORÍA';

CREATE TRIGGER `FUNFICDLT` BEFORE DELETE ON `FUNFIC`
    FOR EACH ROW 
        INSERT INTO `FUNFICA` (`FUNFICAMET`, `FUNFICAUSU`, `FUNFICAFEC`, `FUNFICADIP`, `FUNFICACODOLD`, `FUNFICAESTOLD`, `FUNFICATDCOLD`, `FUNFICATSCOLD`, `FUNFICAECCOLD`, `FUNFICACFUOLD`, `FUNFICANOMOLD`, `FUNFICAAPEOLD`, `FUNFICADOCOLD`, `FUNFICAFHAOLD`, `FUNFICAEMAOLD`, `FUNFICAOBSOLD`) 
        VALUES ('DELETE', OLD.`FUNFICAUS`, NOW(), OLD.`FUNFICAIP`, OLD.`FUNFICCOD`, OLD.`FUNFICEST`, OLD.`FUNFICTDC`, OLD.`FUNFICTSC`, OLD.`FUNFICECC`, OLD.`FUNFICCFU`, OLD.`FUNFICNOM`, OLD.`FUNFICAPE`, OLD.`FUNFICDOC`, OLD.`FUNFICFHA`, OLD.`FUNFICEMA`, OLD.`FUNFICOBS`);

CREATE TRIGGER `FUNFICINS` AFTER INSERT ON `FUNFIC`
    FOR EACH ROW 
        INSERT INTO `FUNFICA` (`FUNFICAMET`, `FUNFICAUSU`, `FUNFICAFEC`, `FUNFICADIP`, `FUNFICACODNEW`, `FUNFICAESTNEW`, `FUNFICATDCNEW`, `FUNFICATSCNEW`, `FUNFICAECCNEW`, `FUNFICACFUNEW`, `FUNFICANOMNEW`, `FUNFICAAPENEW`, `FUNFICADOCNEW`, `FUNFICAFHANEW`, `FUNFICAEMANEW`, `FUNFICAOBSNEW`) 
        VALUES ('INSERT', NEW.`FUNFICAUS`, NOW(), NEW.`FUNFICAIP`, NEW.`FUNFICCOD`, NEW.`FUNFICEST`, NEW.`FUNFICTDC`, NEW.`FUNFICTSC`, NEW.`FUNFICECC`, NEW.`FUNFICCFU`, NEW.`FUNFICNOM`, NEW.`FUNFICAPE`, NEW.`FUNFICDOC`, NEW.`FUNFICFHA`, NEW.`FUNFICEMA`, NEW.`FUNFICOBS`);

CREATE TRIGGER `FUNFICUPD` AFTER UPDATE ON `FUNFIC`
    FOR EACH ROW 
        INSERT INTO `FUNFICA` (`FUNFICAMET`, `FUNFICAUSU`, `FUNFICAFEC`, `FUNFICADIP`, `FUNFICACODOLD`, `FUNFICAESTOLD`, `FUNFICATDCOLD`, `FUNFICATSCOLD`, `FUNFICAECCOLD`, `FUNFICACFUOLD`, `FUNFICANOMOLD`, `FUNFICAAPEOLD`, `FUNFICADOCOLD`, `FUNFICAFHAOLD`, `FUNFICAEMAOLD`, `FUNFICAOBSOLD`, `FUNFICACODNEW`, `FUNFICAESTNEW`, `FUNFICATDCNEW`, `FUNFICATSCNEW`, `FUNFICAECCNEW`, `FUNFICACFUNEW`, `FUNFICANOMNEW`, `FUNFICAAPENEW`, `FUNFICADOCNEW`, `FUNFICAFHANEW`, `FUNFICAEMANEW`, `FUNFICAOBSNEW`) 
        VALUES ('UPDATE', NEW.`FUNFICAUS`, NOW(), NEW.`FUNFICAIP`, OLD.`FUNFICCOD`, OLD.`FUNFICEST`, OLD.`FUNFICTDC`, OLD.`FUNFICTSC`, OLD.`FUNFICECC`, OLD.`FUNFICCFU`, OLD.`FUNFICNOM`, OLD.`FUNFICAPE`, OLD.`FUNFICDOC`, OLD.`FUNFICFHA`, OLD.`FUNFICEMA`, OLD.`FUNFICOBS`, NEW.`FUNFICCOD`, NEW.`FUNFICEST`, NEW.`FUNFICTDC`, NEW.`FUNFICTSC`, NEW.`FUNFICECC`, NEW.`FUNFICCFU`, NEW.`FUNFICNOM`, NEW.`FUNFICAPE`, NEW.`FUNFICDOC`, NEW.`FUNFICFHA`, NEW.`FUNFICEMA`, NEW.`FUNFICOBS`);

ALTER TABLE `FUNFIC` ADD PRIMARY KEY (`FUNFICCOD`);
ALTER TABLE `FUNFIC` MODIFY `FUNFICCOD` mediumint(9) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;
ALTER TABLE `FUNFIC` ADD KEY `FUNFICTDC` (`FUNFICTDC`);
ALTER TABLE `FUNFIC` ADD KEY `FUNFICTSC` (`FUNFICTSC`);
ALTER TABLE `FUNFIC` ADD KEY `FUNFICECC` (`FUNFICECC`);
ALTER TABLE `FUNFIC` ADD CONSTRAINT `FK_FUNFIC_FUNFICTDC` FOREIGN KEY (`FUNFICTDC`) REFERENCES `DOMFIC` (`DOMFICCOD`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `FUNFIC` ADD CONSTRAINT `FK_FUNFIC_FUNFICTSC` FOREIGN KEY (`FUNFICTSC`) REFERENCES `DOMFIC` (`DOMFICCOD`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `FUNFIC` ADD CONSTRAINT `FK_FUNFIC_FUNFICECC` FOREIGN KEY (`FUNFICECC`) REFERENCES `DOMFIC` (`DOMFICCOD`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `FUNFICA` ADD PRIMARY KEY (`FUNFICACOD`);
ALTER TABLE `FUNFICA` MODIFY `FUNFICACOD` int(11) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;