CREATE TABLE IF NOT EXISTS `FUNFAM` (
    `FUNFAMCOD` mediumint(9) NOT NULL COMMENT 'CÓDIGO',
    `FUNFAMEST` char(1) COLLATE utf8_spanish_ci NOT NULL COMMENT 'ESTADO',
    `FUNFAMTPC` mediumint(9) NOT NULL COMMENT 'TIPO PARENTEZCO',
    `FUNFAMFUC` mediumint(9) NOT NULL COMMENT 'FUNCIONARIO',
    `FUNFAMNOM` varchar(100) COLLATE utf8_spanish_ci NOT NULL COMMENT 'PERSONA',
    `FUNFAMEMP` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'EMPRESA',
    `FUNFAMOCU` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'OCUPACIÓN',
    `FUNFAMTEL` varchar(100) COLLATE utf8_spanish_ci COMMENT 'TELEFONO',
    `FUNFAMOBS` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN',
    `FUNFAMAUS` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
    `FUNFAMAFH` datetime NOT NULL COMMENT 'FECHA HORA',
    `FUNFAMAIP` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='FUNCIONARIO DATOS FAMILIARES';

CREATE TABLE IF NOT EXISTS `FUNFAMA` (
    `FUNFAMACOD` int(11) NOT NULL COMMENT 'CÓDIGO',
    `FUNFAMAMET` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'MÉTODO',
    `FUNFAMAUSU` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
    `FUNFAMAFEC` datetime NOT NULL COMMENT 'FECHA HORA',
    `FUNFAMADIP` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP',

    `FUNFAMACODOLD` mediumint(9) NOT NULL COMMENT 'CÓDIGO OLD',
    `FUNFAMAESTOLD` char(1) COLLATE utf8_spanish_ci NOT NULL COMMENT 'ESTADO OLD',
    `FUNFAMATPCOLD` mediumint(9) NOT NULL COMMENT 'TIPO PARENTEZCO OLD',
    `FUNFAMAFUCOLD` mediumint(9) NOT NULL COMMENT 'FUNCIONARIO OLD',
    `FUNFAMANOMOLD` varchar(100) COLLATE utf8_spanish_ci NOT NULL COMMENT 'PERSONA OLD',
    `FUNFAMAEMPOLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'EMPRESA OLD',
    `FUNFAMAOCUOLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'OCUPACIÓN OLD',
    `FUNFAMATELOLD` varchar(100) COLLATE utf8_spanish_ci COMMENT 'TELEFONO OLD',
    `FUNFAMAOBSOLD` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN OLD'

    `FUNFAMACODNEW` mediumint(9) NOT NULL COMMENT 'CÓDIGO',
    `FUNFAMAESTNEW` char(1) COLLATE utf8_spanish_ci NOT NULL COMMENT 'ESTADO',
    `FUNFAMATPCNEW` mediumint(9) NOT NULL COMMENT 'TIPO PARENTEZCO',
    `FUNFAMAFUCNEW` mediumint(9) NOT NULL COMMENT 'FUNCIONARIO',
    `FUNFAMANOMNEW` varchar(100) COLLATE utf8_spanish_ci NOT NULL COMMENT 'PERSONA',
    `FUNFAMAEMPNEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'EMPRESA',
    `FUNFAMAOCUNEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'OCUPACIÓN',
    `FUNFAMATELNEW` varchar(100) COLLATE utf8_spanish_ci COMMENT 'TELEFONO',
    `FUNFAMAOBSNEW` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='FUNCIONARIO DATOS FAMILIARES AUDITORÍA';

CREATE TRIGGER `FUNFAMDLT` BEFORE DELETE ON `FUNFAM`
    FOR EACH ROW 
        INSERT INTO `FUNFAMA` (`FUNFAMAMET`, `FUNFAMAUSU`, `FUNFAMAFEC`, `FUNFAMADIP`, `FUNFAMACODOLD`, `FUNFAMAESTOLD`, `FUNFAMATPCOLD`, `FUNFAMAFUCOLD`, `FUNFAMANOMOLD`, `FUNFAMAEMPOLD`, `FUNFAMAOCUOLD`, `FUNFAMATELOLD`, `FUNFAMAOBSOLD`) 
        VALUES ('DELETE', OLD.`FUNFAMAUS`, NOW(), OLD.`FUNFAMAIP`, OLD.`FUNFAMCOD`, OLD.`FUNFAMEST`, OLD.`FUNFAMTPC`, OLD.`FUNFAMFUC`, OLD.`FUNFAMNOM`, OLD.`FUNFAMEMP`, OLD.`FUNFAMOCU`, OLD.`FUNFAMTEL`, OLD.`FUNFAMOBS`);

CREATE TRIGGER `FUNFAMINS` AFTER INSERT ON `FUNFAM`
    FOR EACH ROW 
        INSERT INTO `FUNFAMA` (`FUNFAMAMET`, `FUNFAMAUSU`, `FUNFAMAFEC`, `FUNFAMADIP`, `FUNFAMACODNEW`, `FUNFAMAESTNEW`, `FUNFAMATPCNEW`, `FUNFAMAFUCNEW`, `FUNFAMANOMNEW`, `FUNFAMAEMPNEW`, `FUNFAMAOCUNEW`, `FUNFAMATELNEW`, `FUNFAMAOBSNEW`) 
        VALUES ('INSERT', NEW.`FUNFAMAUS`, NOW(), NEW.`FUNFAMAIP`, NEW.`FUNFAMCOD`, NEW.`FUNFAMEST`, NEW.`FUNFAMTPC`, NEW.`FUNFAMFUC`, NEW.`FUNFAMNOM`, NEW.`FUNFAMEMP`, NEW.`FUNFAMOCU`, NEW.`FUNFAMTEL`, NEW.`FUNFAMOBS`);

CREATE TRIGGER `FUNFAMUPD` AFTER UPDATE ON `FUNFAM`
    FOR EACH ROW 
        INSERT INTO `FUNFAMA` (`FUNFAMAMET`, `FUNFAMAUSU`, `FUNFAMAFEC`, `FUNFAMADIP`, `FUNFAMACODOLD`, `FUNFAMAESTOLD`, `FUNFAMATPCOLD`, `FUNFAMAFUCOLD`, `FUNFAMANOMOLD`, `FUNFAMAEMPOLD`, `FUNFAMAOCUOLD`, `FUNFAMATELOLD`, `FUNFAMAOBSOLD`, `FUNFAMACODNEW`, `FUNFAMAESTNEW`, `FUNFAMATPCNEW`, `FUNFAMAFUCNEW`, `FUNFAMANOMNEW`, `FUNFAMAEMPNEW`, `FUNFAMAOCUNEW`, `FUNFAMATELNEW`, `FUNFAMAOBSNEW`) 
        VALUES ('UPDATE', NEW.`FUNFAMAUS`, NOW(), NEW.`FUNFAMAIP`, OLD.`FUNFAMCOD`, OLD.`FUNFAMEST`, OLD.`FUNFAMTPC`, OLD.`FUNFAMFUC`, OLD.`FUNFAMNOM`, OLD.`FUNFAMEMP`, OLD.`FUNFAMOCU`, OLD.`FUNFAMTEL`, OLD.`FUNFAMOBS`, NEW.`FUNFAMCOD`, NEW.`FUNFAMEST`, NEW.`FUNFAMTPC`, NEW.`FUNFAMFUC`, NEW.`FUNFAMNOM`, NEW.`FUNFAMEMP`, NEW.`FUNFAMOCU`, NEW.`FUNFAMTEL`, NEW.`FUNFAMOBS`);

ALTER TABLE `FUNFAM` ADD PRIMARY KEY (`FUNFAMCOD`);
ALTER TABLE `FUNFAM` MODIFY `FUNFAMCOD` mediumint(9) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;

ALTER TABLE `FUNFAM` ADD KEY `FUNFAMTPC` (`FUNFAMTPC`);
ALTER TABLE `FUNFAM` ADD CONSTRAINT `FK_FUNTRA_FUNFAMTPC` FOREIGN KEY (`FUNFAMTPC`) REFERENCES `DOMFIC` (`DOMFICCOD`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `FUNFAM` ADD KEY `FUNFAMFUC` (`FUNFAMFUC`);
ALTER TABLE `FUNFAM` ADD CONSTRAINT `FK_FUNTRA_FUNFAMFUC` FOREIGN KEY (`FUNFAMFUC`) REFERENCES `FUNFIC` (`FUNFICCOD`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `FUNFAMA` ADD PRIMARY KEY (`FUNFAMACOD`);
ALTER TABLE `FUNFAMA` MODIFY `FUNFAMACOD` int(11) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;