CREATE TABLE `FUNFIC` (
    `FUNFICCOD` mediumint(9) NOT NULL COMMENT 'CÓDIGO',
    `FUNFICEST` char(1) COLLATE utf8_spanish_ci NOT NULL COMMENT 'ESTADO',
    `FUNFICTDC` mediumint(9) NOT NULL COMMENT 'TIPO DOCUMENTO',
    `FUNFICTSC` mediumint(9) NOT NULL COMMENT 'TIPO SEXO',
    `FUNFICCFU` mediumint(9) NOT NULL COMMENT 'CÓDIGO FUNCIONARIO',
    `FUNFICNOM` varchar(100) COLLATE utf8_spanish_ci NOT NULL COMMENT 'NOMBRE',
    `FUNFICAPE` varchar(100) COLLATE utf8_spanish_ci NOT NULL COMMENT 'APELLIDO',
    `FUNFICDOC` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'DOCUMENTO',
    `FUNFICFHA` datetime NOT NULL COMMENT 'FECHA NACIMIENTO',
    `FUNFICOBS` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN',
    `FUNFICAUS` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
    `FUNFICAFH` datetime NOT NULL COMMENT 'FECHA HORA',
    `FUNFICAIP` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='FUNCIONARIO';

CREATE TABLE `FUNFICA` (
    `FUNFICACOD` int(11) NOT NULL COMMENT 'CÓDIGO',
    `FUNFICAMET` char(20) COLLATE utf8_spanish_ci NULL COMMENT 'MÉTODO',
    `FUNFICAUSU` char(20) COLLATE utf8_spanish_ci NULL COMMENT 'USUARIO',
    `FUNFICAFEC` datetime DEFAULT NULL COMMENT 'FECHA HORA',
    `FUNFICADIP` char(20) COLLATE utf8_spanish_ci NULL COMMENT 'IP',
    `FUNFICACODOLD` mediumint(9) NULL COMMENT 'CÓDIGO OLD',
    `FUNFICAESTOLD` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'ESTADO OLD',
    `FUNFICATDCOLD` mediumint(9) NULL COMMENT 'TIPO DOCUMENTO OLD',
    `FUNFICATSCOLD` mediumint(9) NULL COMMENT 'TIPO SEXO OLD',
    `FUNFICACFUOLD` mediumint(9) NULL COMMENT 'CÓDIGO FUNCIONARIO OLD',
    `FUNFICANOMOLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'NOMBRE OLD',
    `FUNFICAAPEOLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'APELLIDO OLD',
    `FUNFICADOCOLD` char(20) COLLATE utf8_spanish_ci NULL COMMENT 'DOCUMENTO OLD',
    `FUNFICAFHAOLD` datetime NULL COMMENT 'FECHA NACIMIENTO OLD',
    `FUNFICAOBSOLD` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN OLD',
    `FUNFICACODNEW` mediumint(9) NULL COMMENT 'CÓDIGO NEW',
    `FUNFICAESTNEW` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'ESTADO NEW',
    `FUNFICATDCNEW` mediumint(9) NULL COMMENT 'TIPO DOCUMENTO NEW',
    `FUNFICATSCNEW` mediumint(9) NULL COMMENT 'TIPO SEXO NEW',
    `FUNFICACFUNEW` mediumint(9) NULL COMMENT 'CÓDIGO FUNCIONARIO NEW',
    `FUNFICANOMNEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'NOMBRE NEW',
    `FUNFICAAPENEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'APELLIDO NEW',
    `FUNFICADOCNEW` char(20) COLLATE utf8_spanish_ci NULL COMMENT 'DOCUMENTO NEW',
    `FUNFICAFHANEW` datetime NULL COMMENT 'FECHA NACIMIENTO NEW',
    `FUNFICAOBSNEW` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN NEW'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='FUNCIONARIO AUDITORÍA';

ALTER TABLE `FUNFIC` ADD PRIMARY KEY (`FUNFICCOD`);
ALTER TABLE `FUNFIC` MODIFY `FUNFICCOD` mediumint(9) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;
ALTER TABLE `FUNFICA` ADD PRIMARY KEY (`FUNFICACOD`);
ALTER TABLE `FUNFICA` MODIFY `FUNFICACOD` int(11) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;

CREATE TRIGGER `FUNFICDLT` BEFORE DELETE ON `FUNFIC`
    FOR EACH ROW 
        INSERT INTO `FUNFICA` (`FUNFICAMET`, `FUNFICAUSU`, `FUNFICAFEC`, `FUNFICADIP`, `FUNFICACODOLD`, `FUNFICAESTOLD`, `FUNFICATDCOLD`, `FUNFICATSCOLD`, `FUNFICACFUOLD`, `FUNFICANOMOLD`, `FUNFICAAPEOLD`, `FUNFICADOCOLD`, `FUNFICAFHAOLD`, `FUNFICAOBSOLD`) 
        VALUES ('DELETE', OLD.`FUNFICAUS`, OLD.`FUNFICAFH`, OLD.`FUNFICAIP`, OLD.`FUNFICCOD`, OLD.`FUNFICEST`, OLD.`FUNFICTDC`, OLD.`FUNFICTSC`, OLD.`FUNFICCFU`, OLD.`FUNFICNOM`, OLD.`FUNFICAPE`, OLD.`FUNFICDOC`, OLD.`FUNFICFHA`, OLD.`FUNFICOBS`);

CREATE TRIGGER `FUNFICINS` AFTER INSERT ON `FUNFIC`
    FOR EACH ROW 
        INSERT INTO `FUNFICA` (`FUNFICAMET`, `FUNFICAUSU`, `FUNFICAFEC`, `FUNFICADIP`, `FUNFICACODNEW`, `FUNFICAESTNEW`, `FUNFICATDCNEW`, `FUNFICATSCNEW`, `FUNFICACFUNEW`, `FUNFICANOMNEW`, `FUNFICAAPENEW`, `FUNFICADOCNEW`, `FUNFICAFHANEW`, `FUNFICAOBSNEW`) 
        VALUES ('INSERT', NEW.`FUNFICAUS`, NEW.`FUNFICAFH`, NEW.`FUNFICAIP`, NEW.`FUNFICCOD`, NEW.`FUNFICEST`, NEW.`FUNFICTDC`, NEW.`FUNFICTSC`, NEW.`FUNFICCFU`, NEW.`FUNFICNOM`, NEW.`FUNFICAPE`, NEW.`FUNFICDOC`, NEW.`FUNFICFHA`, NEW.`FUNFICOBS`);

CREATE TRIGGER `FUNFICUPD` AFTER UPDATE ON `FUNFIC`
    FOR EACH ROW 
        INSERT INTO `FUNFICA` (`FUNFICAMET`, `FUNFICAUSU`, `FUNFICAFEC`, `FUNFICADIP`, `FUNFICACODOLD`, `FUNFICAESTOLD`, `FUNFICATDCOLD`, `FUNFICATSCOLD`, `FUNFICACFUOLD`, `FUNFICANOMOLD`, `FUNFICAAPEOLD`, `FUNFICADOCOLD`, `FUNFICAFHAOLD`, `FUNFICAOBSOLD`, `FUNFICACODNEW`, `FUNFICAESTNEW`, `FUNFICATDCNEW`, `FUNFICATSCNEW`, `FUNFICACFUNEW`, `FUNFICANOMNEW`, `FUNFICAAPENEW`, `FUNFICADOCNEW`, `FUNFICAFHANEW`, `FUNFICAOBSNEW`) 
        VALUES ('UPDATE', NEW.`FUNFICAUS`, NEW.`FUNFICAFH`, NEW.`FUNFICAIP`, OLD.`FUNFICCOD`, OLD.`FUNFICEST`, OLD.`FUNFICTDC`, OLD.`FUNFICTSC`, OLD.`FUNFICCFU`, OLD.`FUNFICNOM`, OLD.`FUNFICAPE`, OLD.`FUNFICDOC`, OLD.`FUNFICFHA`, OLD.`FUNFICOBS`, NEW.`FUNFICCOD`, NEW.`FUNFICEST`, NEW.`FUNFICTDC`, NEW.`FUNFICTSC`, NEW.`FUNFICCFU`, NEW.`FUNFICNOM`, NEW.`FUNFICAPE`, NEW.`FUNFICDOC`, NEW.`FUNFICFHA`, NEW.`FUNFICOBS`);
