CREATE TABLE IF NOT EXISTS `FUNOAP` (
    `FUNOAPCOD` mediumint(9) NOT NULL COMMENT 'CÓDIGO',
    `FUNOAPEST` char(1) COLLATE utf8_spanish_ci NOT NULL COMMENT 'ESTADO',
    `FUNOAPTMC` char(1) COLLATE utf8_spanish_ci NOT NULL COMMENT 'TIPO MOVILIDAD',
    `FUNOAPTHC` mediumint(9) NOT NULL COMMENT 'TIPO HOBBIES',
    `FUNOAPTPC` mediumint(9) NOT NULL COMMENT 'TIPO PROYECTO',
    `FUNOAPFUC` mediumint(9) NOT NULL COMMENT 'FUNCIONARIO',
    `FUNOAPTHE` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'HOBBIES',
    `FUNOAPTPE` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'PROYECTO',
    `FUNOAPCAD` mediumint(9) NULL COMMENT 'CANTIDAD PERSONAS DEPENDIENTE',
    `FUNOAPCAC` mediumint(9) NULL COMMENT 'CANTIDAD PERSONAS CONTRIBUYENTE',
    `FUNOAPTDT` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'TIEMPO DE TRASLADO',
    `FUNOAPOBS` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN',
    `FUNOAPAUS` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
    `FUNOAPAFH` datetime NOT NULL COMMENT 'FECHA HORA',
    `FUNOAPAIP` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='FUNCIONARIO OTRAS ACTIVIDADES PERSONALES';

CREATE TABLE IF NOT EXISTS `FUNOAPA` (
    `FUNOAPACOD` int(11) NOT NULL COMMENT 'CÓDIGO',
    `FUNOAPAMET` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'MÉTODO',
    `FUNOAPAUSU` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
    `FUNOAPAFEC` datetime NOT NULL COMMENT 'FECHA HORA',
    `FUNOAPADIP` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP',

    `FUNOAPACODOLD` mediumint(9) NULL COMMENT 'CÓDIGO OLD',
    `FUNOAPAESTOLD` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'ESTADO OLD',
    `FUNOAPATMCOLD` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'TIPO MOVILIDAD OLD',
    `FUNOAPATHCOLD` mediumint(9) NULL COMMENT 'TIPO HOBBIES OLD',
    `FUNOAPATPCOLD` mediumint(9) NULL COMMENT 'TIPO PROYECTO OLD',
    `FUNOAPAFUCOLD` mediumint(9) NULL COMMENT 'FUNCIONARIO OLD',
    `FUNOAPATHEOLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'HOBBIES OLD',
    `FUNOAPATPEOLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'PROYECTO OLD',
    `FUNOAPACADOLD` mediumint(9) NULL COMMENT 'CANTIDAD PERSONAS DEPENDIENTE OLD',
    `FUNOAPACACOLD` mediumint(9) NULL COMMENT 'CANTIDAD PERSONAS CONTRIBUYENTE OLD',
    `FUNOAPATDTOLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'TIEMPO DE TRASLADO OLD',
    `FUNOAPAOBSOLD` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN OLD',

    `FUNOAPACODNEW` mediumint(9) NULL COMMENT 'CÓDIGO',
    `FUNOAPAESTNEW` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'ESTADO',
    `FUNOAPATMCNEW` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'TIPO MOVILIDAD',
    `FUNOAPATHCNEW` mediumint(9) NULL COMMENT 'TIPO HOBBIES',
    `FUNOAPATPCNEW` mediumint(9) NULL COMMENT 'TIPO PROYECTO',
    `FUNOAPAFUCNEW` mediumint(9) NULL COMMENT 'FUNCIONARIO',
    `FUNOAPATHENEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'HOBBIES',
    `FUNOAPATPENEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'PROYECTO',
    `FUNOAPACADNEW` mediumint(9) NULL COMMENT 'CANTIDAD PERSONAS DEPENDIENTE',
    `FUNOAPACACNEW` mediumint(9) NULL COMMENT 'CANTIDAD PERSONAS CONTRIBUYENTE',
    `FUNOAPATDTNEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'TIEMPO DE TRASLADO',
    `FUNOAPAOBSNEW` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='FUNCIONARIO OTRAS ACTIVIDADES PERSONALES AUDITORÍA';

CREATE TRIGGER `FUNOAPDLT` BEFORE DELETE ON `FUNOAP`
    FOR EACH ROW 
        INSERT INTO `FUNOAPA` (`FUNOAPAMET`, `FUNOAPAUSU`, `FUNOAPAFEC`, `FUNOAPADIP`,  `FUNOAPACODOLD`, `FUNOAPAESTOLD`, `FUNOAPATMCOLD`, `FUNOAPATHCOLD`, `FUNOAPATPCOLD`, `FUNOAPAFUCOLD`, `FUNOAPATHEOLD`, `FUNOAPATPEOLD`, `FUNOAPACADOLD`, `FUNOAPACACOLD`, `FUNOAPATDTOLD`, `FUNOAPAOBSOLD`) 
        VALUES ('DELETE', OLD.`FUNOAPAUS`, NOW(), OLD.`FUNOAPAIP`, OLD.`FUNOAPCOD`, OLD.`FUNOAPEST`, OLD.`FUNOAPTMC`, OLD.`FUNOAPTHC`, OLD.`FUNOAPTPC`, OLD.`FUNOAPFUC`, OLD.`FUNOAPTHE`, OLD.`FUNOAPTPE`, OLD.`FUNOAPCAD`, OLD.`FUNOAPCAC`, OLD.`FUNOAPTDT`, OLD.`FUNOAPOBS`);

CREATE TRIGGER `FUNOAPINS` AFTER INSERT ON `FUNOAP`
    FOR EACH ROW 
        INSERT INTO `FUNOAPA` (`FUNOAPAMET`, `FUNOAPAUSU`, `FUNOAPAFEC`, `FUNOAPADIP`,  `FUNOAPACODNEW`, `FUNOAPAESTNEW`, `FUNOAPATMCNEW`, `FUNOAPATHCNEW`, `FUNOAPATPCNEW`, `FUNOAPAFUCNEW`, `FUNOAPATHENEW`, `FUNOAPATPENEW`, `FUNOAPACADNEW`, `FUNOAPACACNEW`, `FUNOAPATDTNEW`, `FUNOAPAOBSNEW`) 
        VALUES ('INSERT', NEW.`FUNOAPAUS`, NOW(), NEW.`FUNOAPAIP`, NEW.`FUNOAPCOD`, NEW.`FUNOAPEST`, NEW.`FUNOAPTMC`, NEW.`FUNOAPTHC`, NEW.`FUNOAPTPC`, NEW.`FUNOAPFUC`, NEW.`FUNOAPTHE`, NEW.`FUNOAPTPE`, NEW.`FUNOAPCAD`, NEW.`FUNOAPCAC`, NEW.`FUNOAPTDT`, NEW.`FUNOAPOBS`);

CREATE TRIGGER `FUNOAPUPD` AFTER UPDATE ON `FUNOAP`
    FOR EACH ROW 
        INSERT INTO `FUNOAPA` (`FUNOAPAMET`, `FUNOAPAUSU`, `FUNOAPAFEC`, `FUNOAPADIP`,  `FUNOAPACODOLD`, `FUNOAPAESTOLD`, `FUNOAPATMCOLD`, `FUNOAPATHCOLD`, `FUNOAPATPCOLD`, `FUNOAPAFUCOLD`, `FUNOAPATHEOLD`, `FUNOAPATPEOLD`, `FUNOAPACADOLD`, `FUNOAPACACOLD`, `FUNOAPATDTOLD`, `FUNOAPAOBSOLD`)  
        VALUES ('UPDATE', NEW.`FUNOAPAUS`, NOW(), NEW.`FUNOAPAIP`, OLD.`FUNOAPCOD`, OLD.`FUNOAPEST`, OLD.`FUNOAPTMC`, OLD.`FUNOAPTHC`, OLD.`FUNOAPTPC`, OLD.`FUNOAPFUC`, OLD.`FUNOAPTHE`, OLD.`FUNOAPTPE`, OLD.`FUNOAPCAD`, OLD.`FUNOAPCAC`, OLD.`FUNOAPTDT`, OLD.`FUNOAPOBS`, NEW.`FUNOAPCOD`, NEW.`FUNOAPEST`, NEW.`FUNOAPTMC`, NEW.`FUNOAPTHC`, NEW.`FUNOAPTPC`, NEW.`FUNOAPFUC`, NEW.`FUNOAPTHE`, NEW.`FUNOAPTPE`, NEW.`FUNOAPCAD`, NEW.`FUNOAPCAC`, NEW.`FUNOAPTDT`, NEW.`FUNOAPOBS`);

ALTER TABLE `FUNOAP` ADD PRIMARY KEY (`FUNOAPCOD`);
ALTER TABLE `FUNOAP` MODIFY `FUNOAPCOD` mediumint(9) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;

ALTER TABLE `FUNOAP` ADD KEY `FUNOAPTHC` (`FUNOAPTHC`);
ALTER TABLE `FUNOAP` ADD CONSTRAINT `FK_FUNTRA_FUNOAPTHC` FOREIGN KEY (`FUNOAPTHC`) REFERENCES `DOMFIC` (`DOMFICCOD`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `FUNOAP` ADD KEY `FUNOAPTPC` (`FUNOAPTPC`);
ALTER TABLE `FUNOAP` ADD CONSTRAINT `FK_FUNTRA_FUNOAPTPC` FOREIGN KEY (`FUNOAPTPC`) REFERENCES `DOMFIC` (`DOMFICCOD`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `FUNOAP` ADD KEY `FUNOAPFUC` (`FUNOAPFUC`);
ALTER TABLE `FUNOAP` ADD CONSTRAINT `FK_FUNTRA_FUNOAPFUC` FOREIGN KEY (`FUNOAPFUC`) REFERENCES `FUNFIC` (`FUNFICCOD`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `FUNOAPA` ADD PRIMARY KEY (`FUNOAPACOD`);
ALTER TABLE `FUNOAPA` MODIFY `FUNOAPACOD` int(11) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;