CREATE TABLE IF NOT EXISTS `FUNRPP` (
    `FUNRPPCOD` mediumint(9) NOT NULL COMMENT 'CÓDIGO',
    `FUNRPPEST` char(1) COLLATE utf8_spanish_ci NOT NULL COMMENT 'ESTADO',
    `FUNRPPTCC` mediumint(9) NOT NULL COMMENT 'TIPO CELULAR',
    `FUNRPPTTC` mediumint(9) NOT NULL COMMENT 'TIPO TELEFONO',
    `FUNRPPFUC` mediumint(9) NOT NULL COMMENT 'FUNCIONARIO',
    `FUNRPPNOM` varchar(100) COLLATE utf8_spanish_ci NOT NULL COMMENT 'NOMBRE',
    `FUNRPPTCN` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CELULAR NUMERO',
    `FUNRPPTTN` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'TELEFONO NUMERO',
    `FUNRPPOBS` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN',
    `FUNRPPAUS` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
    `FUNRPPAFH` datetime NOT NULL COMMENT 'FECHA HORA',
    `FUNRPPAIP` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='FUNCIONARIO REFERENCIA PARTICULAR PERSONAL';

CREATE TABLE IF NOT EXISTS `FUNRPPA` (
    `FUNRPPACOD` int(11) NOT NULL COMMENT 'CÓDIGO',
    `FUNRPPAMET` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'MÉTODO',
    `FUNRPPAUSU` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
    `FUNRPPAFEC` datetime NOT NULL COMMENT 'FECHA HORA',
    `FUNRPPADIP` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP',

    `FUNRPPACODOLD` mediumint(9) NULL COMMENT 'CÓDIGO OLD',
    `FUNRPPAESTOLD` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'ESTADO OLD',
    `FUNRPPATCCOLD` mediumint(9) NULL COMMENT 'TIPO CELULAR OLD',
    `FUNRPPATTCOLD` mediumint(9) NULL COMMENT 'TIPO TELEFONO OLD',
    `FUNRPPAFUCOLD` mediumint(9) NULL COMMENT 'FUNCIONARIO OLD',
    `FUNRPPANOMOLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'NOMBRE OLD',
    `FUNRPPATCNOLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CELULAR NUMERO OLD',
    `FUNRPPATTNOLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'TELEFONO NUMERO OLD',
    `FUNRPPAOBSOLD` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN OLD',

    `FUNRPPACODNEW` mediumint(9) NULL COMMENT 'CÓDIGO NEW',
    `FUNRPPAESTNEW` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'ESTADO NEW',
    `FUNRPPATCCNEW` mediumint(9) NULL COMMENT 'TIPO CELULAR NEW',
    `FUNRPPATTCNEW` mediumint(9) NULL COMMENT 'TIPO TELEFONO NEW',
    `FUNRPPAFUCNEW` mediumint(9) NULL COMMENT 'FUNCIONARIO NEW',
    `FUNRPPANOMNEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'NOMBRE NEW',
    `FUNRPPATCNNEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'CELULAR NUMERO NEW',
    `FUNRPPATTNNEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'TELEFONO NUMERO NEW',
    `FUNRPPAOBSNEW` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN NEW'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='FUNCIONARIO REFERENCIA PARTICULAR PERSONAL AUDITORÍA';

CREATE TRIGGER `FUNRPPDLT` BEFORE DELETE ON `FUNRPP`
    FOR EACH ROW 
        INSERT INTO `FUNRPPA` (`FUNRPPAMET`, `FUNRPPAUSU`, `FUNRPPAFEC`, `FUNRPPADIP`, `FUNRPPACODOLD`, `FUNRPPAESTOLD`, `FUNRPPATCCOLD`, `FUNRPPATTCOLD`, `FUNRPPAFUCOLD`, `FUNRPPANOMOLD`, `FUNRPPATCNOLD`, `FUNRPPATTNOLD`, `FUNRPPAOBSOLD`) 
        VALUES ('DELETE', OLD.`FUNRPPAUS`, NOW(), OLD.`FUNRPPAIP`, OLD.`FUNRPPCOD`, OLD.`FUNRPPEST`, OLD.`FUNRPPTCC`, OLD.`FUNRPPTTC`, OLD.`FUNRPPFUC`, OLD.`FUNRPPNOM`, OLD.`FUNRPPTCN`, OLD.`FUNRPPTTN`, OLD.`FUNRPPOBS`);

CREATE TRIGGER `FUNRPPINS` AFTER INSERT ON `FUNRPP`
    FOR EACH ROW 
        INSERT INTO `FUNRPPA` (`FUNRPPAMET`, `FUNRPPAUSU`, `FUNRPPAFEC`, `FUNRPPADIP`, `FUNRPPACODNEW`, `FUNRPPAESTNEW`, `FUNRPPATCCNEW`, `FUNRPPATTCNEW`, `FUNRPPAFUCNEW`, `FUNRPPANOMNEW`, `FUNRPPATCNNEW`, `FUNRPPATTNNEW`, `FUNRPPAOBSNEW`)
        VALUES ('INSERT', NEW.`FUNRPPAUS`, NOW(), NEW.`FUNRPPAIP`, NEW.`FUNRPPCOD`, NEW.`FUNRPPEST`, NEW.`FUNRPPTCC`, NEW.`FUNRPPTTC`, NEW.`FUNRPPFUC`, NEW.`FUNRPPNOM`, NEW.`FUNRPPTCN`, NEW.`FUNRPPTTN`, NEW.`FUNRPPOBS`);

CREATE TRIGGER `FUNRPPUPD` AFTER UPDATE ON `FUNRPP`
    FOR EACH ROW 
        INSERT INTO `FUNRPPA` (`FUNRPPAMET`, `FUNRPPAUSU`, `FUNRPPAFEC`, `FUNRPPADIP`, `FUNRPPACODOLD`, `FUNRPPAESTOLD`, `FUNRPPATCCOLD`, `FUNRPPATTCOLD`, `FUNRPPAFUCOLD`, `FUNRPPANOMOLD`, `FUNRPPATCNOLD`, `FUNRPPATTNOLD`, `FUNRPPAOBSOLD`, `FUNRPPACODNEW`, `FUNRPPAESTNEW`, `FUNRPPATCCNEW`, `FUNRPPATTCNEW`, `FUNRPPAFUCNEW`, `FUNRPPANOMNEW`, `FUNRPPATCNNEW`, `FUNRPPATTNNEW`, `FUNRPPAOBSNEW`) 
        VALUES ('UPDATE', NEW.`FUNRPPAUS`, NOW(), NEW.`FUNRPPAIP`, OLD.`FUNRPPCOD`, OLD.`FUNRPPEST`, OLD.`FUNRPPTCC`, OLD.`FUNRPPTTC`, OLD.`FUNRPPFUC`, OLD.`FUNRPPNOM`, OLD.`FUNRPPTCN`, OLD.`FUNRPPTTN`, OLD.`FUNRPPOBS`, NEW.`FUNRPPCOD`, NEW.`FUNRPPEST`, NEW.`FUNRPPTCC`, NEW.`FUNRPPTTC`, NEW.`FUNRPPFUC`, NEW.`FUNRPPNOM`, NEW.`FUNRPPTCN`, NEW.`FUNRPPTTN`, NEW.`FUNRPPOBS`);

ALTER TABLE `FUNRPP` ADD PRIMARY KEY (`FUNRPPCOD`);
ALTER TABLE `FUNRPP` MODIFY `FUNRPPCOD` mediumint(9) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;

ALTER TABLE `FUNRPP` ADD KEY `FUNRPPTCC` (`FUNRPPTCC`);
ALTER TABLE `FUNRPP` ADD CONSTRAINT `FK_FUNRPP_FUNRPPTCC` FOREIGN KEY (`FUNRPPTCC`) REFERENCES `DOMFIC` (`DOMFICCOD`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `FUNRPP` ADD KEY `FUNRPPTTC` (`FUNRPPTTC`);
ALTER TABLE `FUNRPP` ADD CONSTRAINT `FK_FUNRPP_FUNRPPTTC` FOREIGN KEY (`FUNRPPTTC`) REFERENCES `DOMFIC` (`DOMFICCOD`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `FUNRPP` ADD KEY `FUNRPPFUC` (`FUNRPPFUC`);
ALTER TABLE `FUNRPP` ADD CONSTRAINT `FK_FUNRPP_FUNRPPFUC` FOREIGN KEY (`FUNRPPFUC`) REFERENCES `FUNFIC` (`FUNFICCOD`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `FUNRPPA` ADD PRIMARY KEY (`FUNRPPACOD`);
ALTER TABLE `FUNRPPA` MODIFY `FUNRPPACOD` int(11) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;