CREATE TABLE IF NOT EXISTS `LOCCIU` (
    `LOCCIUCOD` mediumint(9) NOT NULL COMMENT 'CÓDIGO',
    `LOCCIUEST` char(1) COLLATE utf8_spanish_ci NOT NULL COMMENT 'ESTADO',
    `LOCCIUDEC` mediumint(9) NOT NULL COMMENT 'DEPARTAMENTO',
    `LOCCIUNOM` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'NOMBRE',
    `LOCCIUEQU` mediumint(9) NULL COMMENT 'CÓDIGO EQUIVALENCIA',
    `LOCCIUOBS` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN',
    `LOCCIUAUS` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
    `LOCCIUAFH` datetime NOT NULL COMMENT 'FECHA HORA',
    `LOCCIUAIP` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='LOCALIDAD CIUDAD';

CREATE TABLE IF NOT EXISTS `LOCCIUA` (
    `LOCCIUACOD` int(11) NOT NULL COMMENT 'CÓDIGO',
    `LOCCIUAMET` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'MÉTODO',
    `LOCCIUAUSU` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'USUARIO',
    `LOCCIUAFEC` datetime NOT NULL COMMENT 'FECHA HORA',
    `LOCCIUADIP` char(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'IP',

    `LOCCIUACODOLD` mediumint(9) NULL COMMENT 'CÓDIGO OLD',
    `LOCCIUAESTOLD` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'ESTADO OLD',
    `LOCCIUADECOLD` mediumint(9) NULL COMMENT 'DEPARTAMENTO OLD',
    `LOCCIUANOMOLD` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'NOMBRE OLD',
    `LOCCIUAEQUOLD` mediumint(9) NULL COMMENT 'CÓDIGO EQUIVALENCIA OLD',
    `LOCCIUAOBSOLD` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN OLD',

    `LOCCIUACODNEW` mediumint(9) NULL COMMENT 'CÓDIGO NEW',
    `LOCCIUAESTNEW` char(1) COLLATE utf8_spanish_ci NULL COMMENT 'ESTADO NEW',
    `LOCCIUADECNEW` mediumint(9) NULL COMMENT 'DEPARTAMENTO NEW',
    `LOCCIUANOMNEW` varchar(100) COLLATE utf8_spanish_ci NULL COMMENT 'NOMBRE NEW',
    `LOCCIUAEQUNEW` mediumint(9) NULL COMMENT 'CÓDIGO EQUIVALENCIA NEW',
    `LOCCIUAOBSNEW` varchar(5120) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'OBSERVACIÓN NEW'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='LOCALIDAD CIUDAD AUDITORÍA';

CREATE TRIGGER `LOCCIUDLT` BEFORE DELETE ON `LOCCIU`
    FOR EACH ROW 
        INSERT INTO `LOCCIUA` (`LOCCIUAMET`, `LOCCIUAUSU`, `LOCCIUAFEC`, `LOCCIUADIP`, `LOCCIUACODOLD`, `LOCCIUAESTOLD`, `LOCCIUADECOLD`, `LOCCIUANOMOLD`, `LOCCIUAEQUOLD`, `LOCCIUAOBSOLD`)
        VALUES ('DELETE', OLD.`LOCCIUAUS`, NOW(), OLD.`LOCCIUAIP`, OLD.`LOCCIUCOD`, OLD.`LOCCIUEST`, OLD.`LOCCIUDEC`, OLD.`LOCCIUNOM`, OLD.`LOCCIUEQU`, OLD.`LOCCIUOBS`);

CREATE TRIGGER `LOCCIUINS` AFTER INSERT ON `LOCCIU`
    FOR EACH ROW 
        INSERT INTO `LOCCIUA` (`LOCCIUAMET`, `LOCCIUAUSU`, `LOCCIUAFEC`, `LOCCIUADIP`, `LOCCIUACODNEW`, `LOCCIUAESTNEW`, `LOCCIUADECNEW`, `LOCCIUANOMNEW`, `LOCCIUAEQUNEW`, `LOCCIUAOBSNEW`)
        VALUES ('INSERT', NEW.`LOCCIUAUS`, NOW(), NEW.`LOCCIUAIP`, NEW.`LOCCIUCOD`, NEW.`LOCCIUEST`, NEW.`LOCCIUDEC`, NEW.`LOCCIUNOM`, NEW.`LOCCIUEQU`, NEW.`LOCCIUOBS`);

CREATE TRIGGER `LOCCIUUPD` AFTER UPDATE ON `LOCCIU`
    FOR EACH ROW 
        INSERT INTO `LOCCIUA` (`LOCCIUAMET`, `LOCCIUAUSU`, `LOCCIUAFEC`, `LOCCIUADIP`, `LOCCIUACODOLD`, `LOCCIUAESTOLD`, `LOCCIUADECOLD`, `LOCCIUANOMOLD`, `LOCCIUAEQUOLD`, `LOCCIUAOBSOLD`, `LOCCIUACODNEW`, `LOCCIUAESTNEW`, `LOCCIUADECNEW`, `LOCCIUANOMNEW`, `LOCCIUAEQUNEW`, `LOCCIUAOBSNEW`)
        VALUES ('UPDATE', NEW.`LOCCIUAUS`, NOW(), NEW.`LOCCIUAIP`, OLD.`LOCCIUCOD`, OLD.`LOCCIUEST`, OLD.`LOCCIUDEC`, OLD.`LOCCIUNOM`, OLD.`LOCCIUEQU`, OLD.`LOCCIUOBS`, NEW.`LOCCIUCOD`, NEW.`LOCCIUEST`, NEW.`LOCCIUDEC`, NEW.`LOCCIUNOM`, NEW.`LOCCIUEQU`, NEW.`LOCCIUOBS`);

ALTER TABLE `LOCCIU` ADD PRIMARY KEY (`LOCCIUCOD`);
ALTER TABLE `LOCCIU` MODIFY `LOCCIUCOD` mediumint(9) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;

ALTER TABLE `LOCCIU` ADD KEY `LOCCIUDEC` (`LOCCIUDEC`);
ALTER TABLE `LOCCIU` ADD CONSTRAINT `FK_LOCCIU_LOCCIUDEC` FOREIGN KEY (`LOCCIUDEC`) REFERENCES `LOCDEP` (`LOCDEPCOD`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `LOCCIUA` ADD PRIMARY KEY (`LOCCIUACOD`);
ALTER TABLE `LOCCIUA` MODIFY `LOCCIUACOD` int(11) NOT NULL AUTO_INCREMENT COMMENT 'CÓDIGO', AUTO_INCREMENT=0;